/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend.home_page;

import backend.entity.*;
import backend.utility.Utility;
import frontend.pop_up.SystemPopUp;
import frontend.vendor.MainPage;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.event.KeyEvent;
import javax.swing.JFrame;

/**
 *
 * @author Beng Rhui (TP068495), Xuan Jack (TP067678)
 */
public class LoginPage extends javax.swing.JFrame {

    public static JFrame currentFrame;
    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        
        // Set the current frame to the variable
        currentFrame = this;
        
        // Render GUI components
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        translucentBlackBackground = new javax.swing.JPanel();
        logoPicture = new javax.swing.JLabel();
        credentialsPanel = new javax.swing.JPanel();
        loginTitle = new javax.swing.JLabel();
        emailTitle = new javax.swing.JLabel();
        emailInput = new javax.swing.JTextField();
        loginButton = new javax.swing.JButton();
        passwordTitle = new javax.swing.JLabel();
        forgetPasswordLabel = new javax.swing.JLabel();
        passwordInput = new javax.swing.JPasswordField();
        backIcon = new javax.swing.JLabel();
        backgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Food Court System");
        setName("loginFrame"); // NOI18N
        setResizable(false);

        backgroundPanel.setBackground(new java.awt.Color(255, 255, 255));
        backgroundPanel.setPreferredSize(new java.awt.Dimension(1400, 800));
        backgroundPanel.setSize(new java.awt.Dimension(1400, 800));
        backgroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        translucentBlackBackground.setBackground(new java.awt.Color(0, 0, 0, 128));
        translucentBlackBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoPicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/system/logo_light_with_text.png"))); // NOI18N
        translucentBlackBackground.add(logoPicture, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        credentialsPanel.setBackground(new java.awt.Color(0, 0, 0, 200));
        credentialsPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        credentialsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginTitle.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        loginTitle.setForeground(new java.awt.Color(255, 255, 255));
        loginTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginTitle.setText("WELCOME BACK");
        loginTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        credentialsPanel.add(loginTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 580, -1));

        emailTitle.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        emailTitle.setForeground(new java.awt.Color(255, 255, 255));
        emailTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        emailTitle.setText("Email");
        credentialsPanel.add(emailTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 130, 50));

        emailInput.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        emailInput.setForeground(new java.awt.Color(204, 204, 204));
        emailInput.setText("Enter email here");
        emailInput.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 15, 2, 15));
        emailInput.setOpaque(true);
        emailInput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailInputFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailInputFocusLost(evt);
            }
        });
        emailInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                emailInputKeyReleased(evt);
            }
        });
        credentialsPanel.add(emailInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 440, 60));

        loginButton.setBackground(new java.awt.Color(0, 0, 0));
        loginButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        loginButton.setForeground(new java.awt.Color(255, 255, 255));
        loginButton.setText("LOGIN");
        loginButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        loginButton.setOpaque(true);
        loginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginButtonMouseExited(evt);
            }
        });
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        credentialsPanel.add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, 440, 60));

        passwordTitle.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        passwordTitle.setForeground(new java.awt.Color(255, 255, 255));
        passwordTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        passwordTitle.setText("Password");
        credentialsPanel.add(passwordTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 130, 50));

        forgetPasswordLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        forgetPasswordLabel.setForeground(new java.awt.Color(255, 255, 255));
        forgetPasswordLabel.setText("<html>Forgot password? Click <u>me</u>!</html>");
        forgetPasswordLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgetPasswordLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                forgetPasswordLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                forgetPasswordLabelMouseExited(evt);
            }
        });
        credentialsPanel.add(forgetPasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 250, -1));

        passwordInput.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        passwordInput.setForeground(new java.awt.Color(204, 204, 204));
        passwordInput.setText("Enter password here");
        passwordInput.setToolTipText("");
        passwordInput.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 15, 2, 15));
        passwordInput.setEchoChar((char) 0);
        passwordInput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordInputFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordInputFocusLost(evt);
            }
        });
        passwordInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordInputKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passwordInputKeyReleased(evt);
            }
        });
        credentialsPanel.add(passwordInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 440, 60));

        translucentBlackBackground.add(credentialsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 580, 600));

        backIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/system/back_icon.png"))); // NOI18N
        backIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backIconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backIconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backIconMouseExited(evt);
            }
        });
        translucentBlackBackground.add(backIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 50, -1, -1));

        backgroundPanel.add(translucentBlackBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 800));

        backgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/system/login_page_background.jpg"))); // NOI18N
        backgroundPanel.add(backgroundImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailInputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailInputFocusGained
        
        // Take action only if the initial prompt exists
        if (emailInput.getText().equals("Enter email here")) {
            
            // Set the text colour to black and remove all the existing prompt
            emailInput.setForeground(Color.BLACK);
            emailInput.setText("");
        }
    }//GEN-LAST:event_emailInputFocusGained

    private void emailInputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailInputFocusLost
        
        // Perform actions only when input is empty
        if (emailInput.getText().isEmpty()) {
            
            // Set colour back to grey and set the initial prompt
            emailInput.setForeground(new Color(204, 204, 204));
            emailInput.setText("Enter email here");
        }
    }//GEN-LAST:event_emailInputFocusLost

    private void passwordInputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordInputFocusGained
        
        // Get the current prompt
        String currentText = String.valueOf(passwordInput.getPassword());
        
        // Take action only if the initial prompt exists
        if (currentText.equals("Enter password here")) {
            
            // Set the text colour to black and remove all the existing prompt
            passwordInput.setForeground(Color.BLACK);
            passwordInput.setText("");
            passwordInput.setEchoChar('•');
        }
    }//GEN-LAST:event_passwordInputFocusGained

    private void passwordInputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordInputFocusLost

        // Get the current prompt
        String currentText = String.valueOf(passwordInput.getPassword());
        
        // Perform actions only when input is empty
        if (currentText.isEmpty()) {
            
            // Set colour back to grey, display character and set initial prompt
            passwordInput.setEchoChar((char) 0);
            passwordInput.setForeground(new Color(204, 204, 204));
            passwordInput.setText("Enter password here");
        }
    }//GEN-LAST:event_passwordInputFocusLost

    private void loginButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonMouseEntered
        
        // Change the cursor to hand cursor
        loginButton.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        
        // Change the colour of the button
        loginButton.setForeground(Color.BLACK);
        loginButton.setBackground(Color.WHITE);
    }//GEN-LAST:event_loginButtonMouseEntered

    private void loginButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonMouseExited

        // Change the cursor to hand cursor
        loginButton.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        
        // Change the colour of the button
        loginButton.setForeground(Color.WHITE);
        loginButton.setBackground(Color.BLACK);
    }//GEN-LAST:event_loginButtonMouseExited

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed

        // Process the input from user
        String userEmail = emailInput.getText().toLowerCase().strip();
        String userPassword = Utility.generateString(passwordInput.getPassword());

        User currentUser = User.getUser(userEmail, userPassword);

        if (currentUser != null) {
            switch (currentUser) {
                case Admin admin -> System.out.println(admin);
                case Customer customer -> System.out.println(customer);
                case DeliveryRunner runner -> System.out.println(runner);
                case Manager manager -> System.out.println(manager);
                case Vendor vendor -> {
                    
                    // Create a new vendor page
                    MainPage vendorPage = new MainPage();
                    vendorPage.setVisible(true);
                    vendorPage.setLocationRelativeTo(this);
                    
                    // Set the vendor to the new vendor page
                    MainPage.setVendor(vendor);
                }
                
                default -> {
                    
                    // Create a try again message if the current user retrieved is not in the user type (should not happen)
                    SystemPopUp tryAgainMessage = new SystemPopUp(this, "System Error", "Sorry, something wrong has happened.<br>Please try another credentials.", new String[]{"OK"});
                    tryAgainMessage.setVisible(true);
                }

            }
            
            // Dispose the current frame and the home page frame once user logins
            dispose();
            HomePage.currentFrame.dispose();
            
        } else {
            SystemPopUp tryAgainMessage = new SystemPopUp(this, "Incorrect Credentials", "The credentials entered are incorrect.<br>Please try again.", new String[]{"OK"});
            tryAgainMessage.setVisible(true);
        }

    }//GEN-LAST:event_loginButtonActionPerformed

    private void backIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backIconMouseEntered

        // Change cursor
        backIcon.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_backIconMouseEntered

    private void backIconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backIconMouseExited

        // Change cursor
        backIcon.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_backIconMouseExited

    private void backIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backIconMouseClicked

        // Navigate back to home page and set location
        HomePage.currentFrame.setVisible(true);
        HomePage.currentFrame.setLocationRelativeTo(this);
        
        // Dispose the current frame
        dispose();
    }//GEN-LAST:event_backIconMouseClicked

    private void forgetPasswordLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgetPasswordLabelMouseEntered

        // Change cursor
        forgetPasswordLabel.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_forgetPasswordLabelMouseEntered

    private void forgetPasswordLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgetPasswordLabelMouseExited

        // Change cursor
        forgetPasswordLabel.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_forgetPasswordLabelMouseExited

    private void forgetPasswordLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgetPasswordLabelMouseClicked

        // Open the reset password page
        ResetPassword resetPasswordPage = new ResetPassword();
        resetPasswordPage.setVisible(true);
        resetPasswordPage.setLocationRelativeTo(this);
        
        // Make the current frame freeze
        setEnabled(false);
    }//GEN-LAST:event_forgetPasswordLabelMouseClicked

    private void emailInputKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailInputKeyReleased
        
        // When the enter key is pressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            
            // Navigate to password input field
            passwordInput.requestFocus();
            passwordInput.selectAll();
        }
    }//GEN-LAST:event_emailInputKeyReleased

    private void passwordInputKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordInputKeyReleased
       
        // When the enter key is pressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            
            // Reset the colour of the button
            loginButton.setForeground(Color.WHITE);
            loginButton.setBackground(Color.BLACK);
            
            // Run the button
            loginButton.doClick();
        }
    }//GEN-LAST:event_passwordInputKeyReleased

    private void passwordInputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordInputKeyPressed
        
        // When pressing enter key
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            
            // Change the colour of the button
            loginButton.setForeground(Color.BLACK);
            loginButton.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_passwordInputKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backIcon;
    private javax.swing.JLabel backgroundImage;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JPanel credentialsPanel;
    private javax.swing.JTextField emailInput;
    private javax.swing.JLabel emailTitle;
    private javax.swing.JLabel forgetPasswordLabel;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel loginTitle;
    private javax.swing.JLabel logoPicture;
    private javax.swing.JPasswordField passwordInput;
    private javax.swing.JLabel passwordTitle;
    private javax.swing.JPanel translucentBlackBackground;
    // End of variables declaration//GEN-END:variables
}
