package main;

import backend.file_io.FileIO;
import frontend.home_page.HomePage;

import javax.swing.*;

public class Main {

    public static void main(String[] args) {

        // Read all the files before running the system
        FileIO.readAllFIle();

        // Set the look and feel of system (code autogenerated from Netbeans Drag and Drop, instead of Nimbus, Metal is used)
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException |
                 UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        // Code to run main page (autogenerated by Netbeans Drag and Drop too)
        java.awt.EventQueue.invokeLater(
                () -> new HomePage().setVisible(true)
        );
    }
}
