/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frontend.manager;

/**
 *
 * @author Chun Ming
 */
public class CheckVendor extends javax.swing.JPanel {

    private ManagerFrame managerFrame;

    public CheckVendor() {
        initComponents();
        initLayout();
    }

    public void setManagerFrame(ManagerFrame managerFrame) {
        this.managerFrame = managerFrame;
    }

    private void initLayout() {
        this.setBackground(new java.awt.Color(255, 251, 233, 240));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vendorScrollList = new javax.swing.JScrollPane();
        searchNameLabel = new javax.swing.JLabel();
        searchName = new javax.swing.JTextField();
        searchStoreIdLabel = new javax.swing.JLabel();
        searchStoreId = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 251, 233));
        setLayout(null);
        add(vendorScrollList);
        vendorScrollList.setBounds(72, 110, 1260, 500);

        searchNameLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        searchNameLabel.setText("<html>Search <br> by Name:</html>");
        add(searchNameLabel);
        searchNameLabel.setBounds(70, 40, 180, 55);

        searchName.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        searchName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        add(searchName);
        searchName.setBounds(250, 40, 470, 60);

        searchStoreIdLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        searchStoreIdLabel.setText("<html>Search by <br>Store ID:</html>");
        add(searchStoreIdLabel);
        searchStoreIdLabel.setBounds(730, 40, 160, 60);

        searchStoreId.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        searchStoreId.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        add(searchStoreId);
        searchStoreId.setBounds(890, 40, 440, 60);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField searchName;
    private javax.swing.JLabel searchNameLabel;
    private javax.swing.JTextField searchStoreId;
    private javax.swing.JLabel searchStoreIdLabel;
    private javax.swing.JScrollPane vendorScrollList;
    // End of variables declaration//GEN-END:variables
}
