/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frontend.manager;

import backend.entity.Feedback;

/**
 *
 * @author Chun Ming (TP068983), Beng Rhui (TP068495)
 */
public class FeedbackDetailsPanel extends javax.swing.JPanel {

    private Feedback currentFeedback;
    
    /**
     * Creates new form FeedbackDetailsPanel
     */
    public FeedbackDetailsPanel(Feedback feedback) {
        
        // Set current feedback
        currentFeedback = feedback;
        
        // Render GUI components
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        feedbackTitleScrollPane = new javax.swing.JScrollPane();
        feedbackTItleLabel = new javax.swing.JTextArea();
        feedbackDescriptionScrollPane = new javax.swing.JScrollPane();
        feedbackDescriptionLabel = new javax.swing.JTextArea();
        lookIcon = new javax.swing.JLabel();

        setBackground(new java.awt.Color(227, 202, 165));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        setMaximumSize(new java.awt.Dimension(400, 150));
        setMinimumSize(new java.awt.Dimension(400, 150));
        setSize(new java.awt.Dimension(400, 150));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        feedbackTitleScrollPane.setBorder(null);
        feedbackTitleScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        feedbackTitleScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        feedbackTItleLabel.setBackground(new java.awt.Color(227, 202, 165));
        feedbackTItleLabel.setColumns(20);
        feedbackTItleLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        feedbackTItleLabel.setRows(1);
        feedbackTItleLabel.setText(currentFeedback.getFeedbackTitle());
        feedbackTItleLabel.setBorder(null);
        feedbackTItleLabel.setCaretColor(new java.awt.Color(227, 202, 165));
        feedbackTItleLabel.setCaretPosition(0);
        feedbackTitleScrollPane.setViewportView(feedbackTItleLabel);

        add(feedbackTitleScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 280, 30));

        feedbackDescriptionScrollPane.setBorder(null);
        feedbackDescriptionScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        feedbackDescriptionScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        feedbackDescriptionLabel.setBackground(new java.awt.Color(227, 202, 165));
        feedbackDescriptionLabel.setColumns(20);
        feedbackDescriptionLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        feedbackDescriptionLabel.setLineWrap(true);
        feedbackDescriptionLabel.setRows(2);
        feedbackDescriptionLabel.setText(currentFeedback.getFeedbackDetails());
        feedbackDescriptionLabel.setWrapStyleWord(true);
        feedbackDescriptionLabel.setBorder(null);
        feedbackDescriptionLabel.setCaretColor(new java.awt.Color(227, 202, 165));
        feedbackDescriptionLabel.setCaretPosition(0);
        feedbackDescriptionScrollPane.setViewportView(feedbackDescriptionLabel);

        add(feedbackDescriptionScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 330, 50));

        lookIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lookIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/system/search_icon.png"))); // NOI18N
        lookIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lookIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lookIconMouseClicked(evt);
            }
        });
        add(lookIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 50, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void lookIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lookIconMouseClicked

        // Call the feedback reply form
        FeedbackReplyForm replyForm = new FeedbackReplyForm(currentFeedback);
        replyForm.setVisible(true);
        replyForm.setLocationRelativeTo(MainPage.currentFrame);
        
        // Disable the parent frame
        MainPage.currentFrame.setEnabled(false);
    }//GEN-LAST:event_lookIconMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea feedbackDescriptionLabel;
    private javax.swing.JScrollPane feedbackDescriptionScrollPane;
    private javax.swing.JTextArea feedbackTItleLabel;
    private javax.swing.JScrollPane feedbackTitleScrollPane;
    private javax.swing.JLabel lookIcon;
    // End of variables declaration//GEN-END:variables
}
