/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend.manager;

import backend.entity.Item;
import backend.entity.Vendor;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Chun Ming (TP068983), Beng Rhui (TP068495)
 */
public class ItemPanel extends javax.swing.JFrame {

    private static Vendor currentVendor;
    public static JFrame currentFrame;
    
    /**
     * Creates new form ItemPanel
     */
    public ItemPanel(Vendor vendor) {

        // Set the current vendor
        currentVendor = vendor;
        
        // Set the current frame
        currentFrame = this;
        
        // Render GUI components
        initComponents();
        
        // Update the panel
        updatePanel();
    }
    
    /**
     * This method helps to update the panel consisting of the item details.
     */
    public static void updatePanel() {
        
        // Remove all components in the panel
        itemPanel.removeAll();
        
        // Retrieve the list of items
        ArrayList<Item> itemList = Item.getItemList(currentVendor);
        
        // If there is no item
        if (itemList.isEmpty()) {
        
            // Generate an empty label and panel to accommodate the message
            JPanel emptyPanel = new JPanel(new FlowLayout(FlowLayout.LEFT));
            JLabel emptyLabel = new JLabel("No item exists for the vendor.");
            
            // Customize the label and panel
            emptyPanel.setBackground(new Color(255, 251, 233));
            emptyLabel.setFont(new Font("Arial", Font.PLAIN, 18));
            
            // Add label to panel, and add panel to container
            emptyPanel.add(emptyLabel);
            itemPanel.add(emptyPanel);
            
        } else {
            
            // Loop through each item
            for (Item item : itemList) {
                JPanel itemDetails = new ItemDetailsPanel(item, false, true);
                itemPanel.add(itemDetails);
            }
        }
        
        // Refresh the pane after done
        itemPanel.revalidate();
        itemPanel.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        itemTitle = new javax.swing.JLabel();
        closeIcon = new javax.swing.JLabel();
        itemPanelScrollPane = new javax.swing.JScrollPane();
        itemPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Vendor Item Listing");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backgroundPanel.setBackground(new java.awt.Color(255, 251, 233));
        backgroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        itemTitle.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        itemTitle.setText("Vendor Item");
        backgroundPanel.add(itemTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        closeIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/system/cancel_icon.png"))); // NOI18N
        closeIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeIconMouseClicked(evt);
            }
        });
        backgroundPanel.add(closeIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(812, 40, 60, 60));

        itemPanelScrollPane.setBackground(new java.awt.Color(255, 251, 233));
        itemPanelScrollPane.setBorder(null);
        itemPanelScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        itemPanelScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        itemPanel.setBackground(new java.awt.Color(255, 251, 233));
        itemPanel.setLayout(new java.awt.GridLayout(0, 2, 10, 10));
        itemPanelScrollPane.setViewportView(itemPanel);

        backgroundPanel.add(itemPanelScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 810, 410));

        getContentPane().add(backgroundPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeIconMouseClicked

        // Enable the parent frame
        UserOverviewPopUp.currentFrame.setEnabled(true);
        
        // Dispose the current frame
        dispose();
    }//GEN-LAST:event_closeIconMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ItemPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ItemPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ItemPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ItemPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ItemPanel(currentVendor).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JLabel closeIcon;
    private static javax.swing.JPanel itemPanel;
    private javax.swing.JScrollPane itemPanelScrollPane;
    private javax.swing.JLabel itemTitle;
    // End of variables declaration//GEN-END:variables
}
