/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frontend.manager;

import backend.entity.DeliveryRunner;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.Font;
import java.util.ArrayList;
import java.util.stream.Collectors;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Chun Ming (TP068983), Beng Rhui (TP068495)
 */
public class RunnerPanel extends javax.swing.JPanel {

    private static ArrayList<DeliveryRunner> runnerList;
    
    /**
     * Creates new form RunnerPane
     */
    public RunnerPanel() {
        
        // Render GUI components
        initComponents();
        
        // Initialize the list of customers
        runnerList = DeliveryRunner.getDeliveryRunnerList();
        
        // Update panel
        updatePanel();
    }

    public void filterByRunnerName(String input) {
    
        // Filter the list
        runnerList = DeliveryRunner.getDeliveryRunnerList().stream()
                .filter(runner -> runner.getName().toLowerCase().contains(input.toLowerCase()))
                .collect(Collectors.toCollection(ArrayList::new));
        
        // Update panel
        updatePanel();
    }
    
    public void filterByContactNumber(String input) {
        
        // Filter the list
        runnerList = DeliveryRunner.getDeliveryRunnerList().stream()
                .filter(runner -> runner.getContactNumber().replace("-", "").contains(input.replace("-", "")))
                .collect(Collectors.toCollection(ArrayList::new));
        
        // Update panel
        updatePanel();
    }
    
    public void updatePanel() {
        
        // Clear the contents on the panel
        runnerDetailsPanel.removeAll();
        
        // If there is no vendor
        if (runnerList.isEmpty()) {
        
            // Create a JLabel and JPanel to display message
            JPanel emptyPanel = new JPanel(new FlowLayout(FlowLayout.LEFT));
            JLabel emptyLabel = new JLabel("No delivery runner available.");
            
            // Set attributes to the label
            emptyLabel.setFont(new Font("Arial", Font.PLAIN, 18));
            
            // Add label to panel
            emptyPanel.add(emptyLabel);
            emptyPanel.setBackground(new Color(255, 251, 233));
            
            // Add panel to the container
            runnerDetailsPanel.add(emptyPanel);
            
        } else {
        
            // Loop through vendor list
            for (DeliveryRunner runner : runnerList) {

                // Create panel to show vendor information
                JPanel panel = new UserInformationPanel(runner);
                runnerDetailsPanel.add(panel);
            }
            
            // Add empty panels if the number of vendors is not sufficient
            for (int i = runnerList.size() + 1; i < 7; i ++) {
                
                // Create empty panels
                JPanel emptyPanel = new JPanel();
                
                // Set background
                emptyPanel.setBackground(new Color(255, 251, 233));
                
                // Add the empty panel to container
                runnerDetailsPanel.add(emptyPanel);
            }
        }
        
        // Refresh panel
        runnerDetailsPanel.revalidate();
        runnerDetailsPanel.repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchRunnerNameLabel = new javax.swing.JLabel();
        searchRunnerNameField = new javax.swing.JTextField();
        searchContactNumberLabel = new javax.swing.JLabel();
        searchContactNumberField = new javax.swing.JTextField();
        runnerScrollPane = new javax.swing.JScrollPane();
        runnerDetailsPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 251, 233));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchRunnerNameLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        searchRunnerNameLabel.setText("<html>Search by name:</html>");
        add(searchRunnerNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 80, 70));

        searchRunnerNameField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        searchRunnerNameField.setForeground(new java.awt.Color(204, 204, 204));
        searchRunnerNameField.setText("Enter Delivery Runner Name");
        searchRunnerNameField.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), javax.swing.BorderFactory.createEmptyBorder(2, 15, 2, 15)));
        searchRunnerNameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchRunnerNameFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchRunnerNameFieldFocusLost(evt);
            }
        });
        searchRunnerNameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchRunnerNameFieldKeyReleased(evt);
            }
        });
        add(searchRunnerNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 570, 50));

        searchContactNumberLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        searchContactNumberLabel.setText("<html>Search by contact no:</html>");
        add(searchContactNumberLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 40, 120, 70));

        searchContactNumberField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        searchContactNumberField.setForeground(new java.awt.Color(204, 204, 204));
        searchContactNumberField.setText("Enter Contact Number");
        searchContactNumberField.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), javax.swing.BorderFactory.createEmptyBorder(2, 15, 2, 15)));
        searchContactNumberField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchContactNumberFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchContactNumberFieldFocusLost(evt);
            }
        });
        searchContactNumberField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchContactNumberFieldKeyReleased(evt);
            }
        });
        add(searchContactNumberField, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 50, 400, 50));

        runnerScrollPane.setBorder(null);

        runnerDetailsPanel.setBackground(new java.awt.Color(255, 251, 233));
        runnerDetailsPanel.setLayout(new java.awt.GridLayout(0, 3, 10, 10));
        runnerScrollPane.setViewportView(runnerDetailsPanel);

        add(runnerScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 132, 1220, 450));
    }// </editor-fold>//GEN-END:initComponents

    private void searchRunnerNameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchRunnerNameFieldFocusGained

        // If prompt is still there
        if (searchRunnerNameField.getText().equals("Enter Delivery Runner Name")) {

            // Remove the prompt
            searchRunnerNameField.setText("");

            // Change text to black
            searchRunnerNameField.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_searchRunnerNameFieldFocusGained

    private void searchRunnerNameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchRunnerNameFieldFocusLost

        // If input is empty
        if (searchRunnerNameField.getText().isBlank()) {

            // Set prompt
            searchRunnerNameField.setText("Enter Delivery Runner Name");

            // Change text to grey
            searchRunnerNameField.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_searchRunnerNameFieldFocusLost

    private void searchRunnerNameFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchRunnerNameFieldKeyReleased

        // Clear the stall name field
        searchContactNumberField.setText("Enter Contact Number");
        searchContactNumberField.setForeground(new Color(204, 204, 204));

        // Filter panel based on input
        String input = searchRunnerNameField.getText();
        filterByRunnerName(input);
    }//GEN-LAST:event_searchRunnerNameFieldKeyReleased

    private void searchContactNumberFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchContactNumberFieldFocusGained

        // If prompt is still there
        if (searchContactNumberField.getText().equals("Enter Contact Number")) {

            // Remove the prompt
            searchContactNumberField.setText("");

            // Change text to black
            searchContactNumberField.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_searchContactNumberFieldFocusGained

    private void searchContactNumberFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchContactNumberFieldFocusLost

        // If input is empty
        if (searchContactNumberField.getText().isBlank()) {

            // Set prompt
            searchContactNumberField.setText("Enter Contact Number");

            // Change text to grey
            searchContactNumberField.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_searchContactNumberFieldFocusLost

    private void searchContactNumberFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchContactNumberFieldKeyReleased

        // Clear the vendor name field
        searchRunnerNameField.setText("Enter Delivery Runner Name");
        searchRunnerNameField.setForeground(new Color(204, 204, 204));

        // Filter panel based on input
        String input = searchContactNumberField.getText();
        filterByContactNumber(input);
    }//GEN-LAST:event_searchContactNumberFieldKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JPanel runnerDetailsPanel;
    private javax.swing.JScrollPane runnerScrollPane;
    private javax.swing.JTextField searchContactNumberField;
    private javax.swing.JLabel searchContactNumberLabel;
    private javax.swing.JTextField searchRunnerNameField;
    private javax.swing.JLabel searchRunnerNameLabel;
    // End of variables declaration//GEN-END:variables
}
