/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frontend.manager;

import backend.entity.Vendor;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.Font;
import java.util.ArrayList;
import java.util.stream.Collectors;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author limbengrhui
 */
public class VendorPanel extends javax.swing.JPanel {

    private static ArrayList<Vendor> vendorList;
    
    /**
     * Creates new form VendorPanel
     */
    public VendorPanel() {
        
        // Render GUI components
        initComponents();
        
        // Initialize the list of customers
        vendorList = Vendor.getVendorList();
        
        // Update panel
        updatePanel();
    }

    public void filterByVendorName(String input) {
    
        // Filter the list
        vendorList = Vendor.getVendorList().stream()
                .filter(vendor -> vendor.getName().toLowerCase().contains(input.toLowerCase()))
                .collect(Collectors.toCollection(ArrayList::new));
        
        // Update panel
        updatePanel();
    }
    
    public void filterByStallName(String input) {
        
        // Filter the list
        vendorList = Vendor.getVendorList().stream()
                .filter(vendor -> vendor.getStall().getStallName().toLowerCase().contains(input.toLowerCase()))
                .collect(Collectors.toCollection(ArrayList::new));
        
        // Update panel
        updatePanel();
    }
    
    public void updatePanel() {
        
        // Remove everything on the panel
        vendorDetailsPanel.removeAll();
        
        // If there is no vendor
        if (vendorList.isEmpty()) {
        
            // Create a JLabel and JPanel to display message
            JPanel emptyPanel = new JPanel(new FlowLayout(FlowLayout.LEFT));
            JLabel emptyLabel = new JLabel("No vendor available.");
            
            // Set attributes to the label
            emptyLabel.setFont(new Font("Arial", Font.PLAIN, 18));
            
            // Add label to panel
            emptyPanel.add(emptyLabel);
            emptyPanel.setBackground(new Color(255, 251, 233));
            
            // Add panel to the container
            vendorDetailsPanel.add(emptyPanel);
            
        } else {
        
            // Loop through vendor list
            for (Vendor vendor : vendorList) {

                // Create panel to show vendor information
                JPanel panel = new UserInformationPanel(vendor);
                vendorDetailsPanel.add(panel);
            }
            
            // Add empty panels if the number of vendors is not sufficient
            for (int i = vendorList.size() + 1; i < 7; i ++) {
                
                // Create empty panels
                JPanel emptyPanel = new JPanel();
                
                // Set background
                emptyPanel.setBackground(new Color(255, 251, 233));
                
                // Add the empty panel to container
                vendorDetailsPanel.add(emptyPanel);
            }
        }
        
        // Refresh panel
        vendorDetailsPanel.revalidate();
        vendorDetailsPanel.repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchVendorNameLabel = new javax.swing.JLabel();
        searchVendorNameField = new javax.swing.JTextField();
        searchStallNameLabel = new javax.swing.JLabel();
        searchStallNameField = new javax.swing.JTextField();
        vendorScrollPane = new javax.swing.JScrollPane();
        vendorDetailsPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 251, 233));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchVendorNameLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        searchVendorNameLabel.setText("<html>Search by vendor name:</html>");
        add(searchVendorNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 110, 70));

        searchVendorNameField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        searchVendorNameField.setForeground(new java.awt.Color(204, 204, 204));
        searchVendorNameField.setText("Enter Vendor Name");
        searchVendorNameField.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), javax.swing.BorderFactory.createEmptyBorder(2, 15, 2, 15)));
        searchVendorNameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchVendorNameFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchVendorNameFieldFocusLost(evt);
            }
        });
        searchVendorNameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchVendorNameFieldKeyReleased(evt);
            }
        });
        add(searchVendorNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 570, 50));

        searchStallNameLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        searchStallNameLabel.setText("<html>Search by stall name:</html>");
        add(searchStallNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 40, 120, 70));

        searchStallNameField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        searchStallNameField.setForeground(new java.awt.Color(204, 204, 204));
        searchStallNameField.setText("Enter Stall Name");
        searchStallNameField.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), javax.swing.BorderFactory.createEmptyBorder(2, 15, 2, 15)));
        searchStallNameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchStallNameFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchStallNameFieldFocusLost(evt);
            }
        });
        searchStallNameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchStallNameFieldKeyReleased(evt);
            }
        });
        add(searchStallNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 50, 400, 50));

        vendorScrollPane.setBorder(null);

        vendorDetailsPanel.setBackground(new java.awt.Color(255, 251, 233));
        vendorDetailsPanel.setLayout(new java.awt.GridLayout(0, 3, 10, 10));
        vendorScrollPane.setViewportView(vendorDetailsPanel);

        add(vendorScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 132, 1220, 450));
    }// </editor-fold>//GEN-END:initComponents

    private void searchVendorNameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchVendorNameFieldFocusGained

        // If prompt is still there
        if (searchVendorNameField.getText().equals("Enter Vendor Name")) {

            // Remove the prompt
            searchVendorNameField.setText("");

            // Change text to black
            searchVendorNameField.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_searchVendorNameFieldFocusGained

    private void searchVendorNameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchVendorNameFieldFocusLost

        // If input is empty
        if (searchVendorNameField.getText().isBlank()) {

            // Set prompt
            searchVendorNameField.setText("Enter Vendor Name");

            // Change text to grey
            searchVendorNameField.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_searchVendorNameFieldFocusLost

    private void searchVendorNameFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchVendorNameFieldKeyReleased

        // Clear the stall name field
        searchStallNameField.setText("Enter Stall Name");
        searchStallNameField.setForeground(new Color(204, 204, 204));

        // Filter panel based on input
        String input = searchVendorNameField.getText();
        filterByVendorName(input);
    }//GEN-LAST:event_searchVendorNameFieldKeyReleased

    private void searchStallNameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchStallNameFieldFocusGained

        // If prompt is still there
        if (searchStallNameField.getText().equals("Enter Stall Name")) {

            // Remove the prompt
            searchStallNameField.setText("");

            // Change text to black
            searchStallNameField.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_searchStallNameFieldFocusGained

    private void searchStallNameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchStallNameFieldFocusLost

        // If input is empty
        if (searchStallNameField.getText().isBlank()) {

            // Set prompt
            searchStallNameField.setText("Enter Stall Name");

            // Change text to grey
            searchStallNameField.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_searchStallNameFieldFocusLost

    private void searchStallNameFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchStallNameFieldKeyReleased

        // Clear the vendor name field
        searchVendorNameField.setText("Enter Vendor Name");
        searchVendorNameField.setForeground(new Color(204, 204, 204));

        // Filter panel based on input
        String input = searchStallNameField.getText();
        filterByStallName(input);
    }//GEN-LAST:event_searchStallNameFieldKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField searchStallNameField;
    private javax.swing.JLabel searchStallNameLabel;
    private javax.swing.JTextField searchVendorNameField;
    private javax.swing.JLabel searchVendorNameLabel;
    private static javax.swing.JPanel vendorDetailsPanel;
    private javax.swing.JScrollPane vendorScrollPane;
    // End of variables declaration//GEN-END:variables
}
