/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import java.awt.Color;
import java.awt.Cursor;

/**
 *
 * @author User
 */
public class AdminFrame extends javax.swing.JFrame {

    /**
     * Creates new form AdminFrame
     */
    public AdminFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AdminHomePane = new javax.swing.JLayeredPane();
        Title1 = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        Logout = new javax.swing.JLabel();
        Description = new javax.swing.JLabel();
        ManageStore = new javax.swing.JButton();
        ManageUser = new javax.swing.JButton();
        TopUpCredit = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin_Home");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        setSize(new java.awt.Dimension(1400, 800));

        AdminHomePane.setMaximumSize(new java.awt.Dimension(1400, 800));
        AdminHomePane.setPreferredSize(new java.awt.Dimension(1400, 800));

        Title1.setFont(new java.awt.Font("Segoe UI", 3, 60)); // NOI18N
        Title1.setForeground(new java.awt.Color(255, 255, 255));
        Title1.setText("Welcome Back, Admin!");
        AdminHomePane.add(Title1);
        Title1.setBounds(380, 190, 655, 81);

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/system/logo_light.png"))); // NOI18N
        Logo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LogoMouseEntered(evt);
            }
        });
        AdminHomePane.add(Logo);
        Logo.setBounds(55, 19, 120, 112);

        Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/system/logout_icon.png"))); // NOI18N
        AdminHomePane.add(Logout);
        Logout.setBounds(1300, 20, 74, 80);

        Description.setFont(new java.awt.Font("Segoe UI", 2, 48)); // NOI18N
        Description.setForeground(new java.awt.Color(255, 255, 255));
        Description.setText("“Time to start your work for today!”");
        AdminHomePane.add(Description);
        Description.setBounds(340, 270, 735, 64);

        ManageStore.setBackground(new java.awt.Color(227, 202, 165));
        ManageStore.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ManageStore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/system/manage_store_icon.png"))); // NOI18N
        ManageStore.setText("Manage Store");
        ManageStore.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        ManageStore.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ManageStore.setPreferredSize(new java.awt.Dimension(200, 50));
        ManageStore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageStoreActionPerformed(evt);
            }
        });
        AdminHomePane.add(ManageStore);
        ManageStore.setBounds(590, 470, 220, 60);

        ManageUser.setBackground(new java.awt.Color(227, 202, 165));
        ManageUser.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ManageUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/system/team_icon.png"))); // NOI18N
        ManageUser.setText("Manage User");
        ManageUser.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        ManageUser.setPreferredSize(new java.awt.Dimension(200, 50));
        ManageUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ManageUserMouseEntered(evt);
            }
        });
        ManageUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageUserActionPerformed(evt);
            }
        });
        AdminHomePane.add(ManageUser);
        ManageUser.setBounds(440, 390, 220, 60);

        TopUpCredit.setBackground(new java.awt.Color(173, 139, 115));
        TopUpCredit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TopUpCredit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/system/wallet_icon.png"))); // NOI18N
        TopUpCredit.setText("Top Up Credit");
        TopUpCredit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        TopUpCredit.setPreferredSize(new java.awt.Dimension(200, 50));
        TopUpCredit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TopUpCreditActionPerformed(evt);
            }
        });
        AdminHomePane.add(TopUpCredit);
        TopUpCredit.setBounds(730, 390, 220, 60);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/system/admin_background_1.png"))); // NOI18N
        AdminHomePane.add(Background);
        Background.setBounds(0, 0, 1400, 800);

        getContentPane().add(AdminHomePane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_LogoMouseClicked

    private void LogoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoMouseEntered
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_LogoMouseEntered

    private void ManageStoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageStoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ManageStoreActionPerformed

    private void ManageUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ManageUserActionPerformed

    private void TopUpCreditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TopUpCreditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TopUpCreditActionPerformed

    private void ManageUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageUserMouseEntered
        //ManageUser.setCursor(new Cursor(Cursor.HAND_CURSOR));
        ManageUser.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_ManageUserMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane AdminHomePane;
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Description;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel Logout;
    private javax.swing.JButton ManageStore;
    private javax.swing.JButton ManageUser;
    private javax.swing.JLabel Title1;
    private javax.swing.JButton TopUpCredit;
    // End of variables declaration//GEN-END:variables
}
