/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend.Customer;

/**
 *
 * @author Lenovo
 */
public class CustomerHomePage extends javax.swing.JFrame {

    /**
     * Creates new form CustomerHomePage
     */
    public CustomerHomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        top_panel = new javax.swing.JPanel();
        logo_light = new javax.swing.JLabel();
        home_page = new javax.swing.JLabel();
        order_history = new javax.swing.JLabel();
        e_wallet = new javax.swing.JLabel();
        issue_and_support = new javax.swing.JLabel();
        welcome_text = new javax.swing.JLabel();
        settings_icon = new javax.swing.JLabel();
        notification_icon = new javax.swing.JLabel();
        back_icon = new javax.swing.JLabel();
        customer_background = new javax.swing.JLabel();
        bottom_panel = new javax.swing.JPanel();
        current_orders_text = new javax.swing.JLabel();
        current_orders_panel = new javax.swing.JScrollPane();
        current_orders_text1 = new javax.swing.JLabel();
        categories_panel = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1400, 800));
        setSize(new java.awt.Dimension(1400, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        top_panel.setBackground(new java.awt.Color(102, 102, 102));
        top_panel.setLayout(null);

        logo_light.setBackground(new java.awt.Color(255, 255, 255));
        logo_light.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/system/logo_light.png"))); // NOI18N
        top_panel.add(logo_light);
        logo_light.setBounds(-10, 0, 250, 150);

        home_page.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        home_page.setForeground(new java.awt.Color(255, 255, 255));
        home_page.setText("Home Page");
        home_page.setAlignmentY(0.0F);
        home_page.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        home_page.setIconTextGap(0);
        home_page.setMaximumSize(new java.awt.Dimension(130, 30));
        home_page.setMinimumSize(new java.awt.Dimension(130, 30));
        home_page.setName(""); // NOI18N
        home_page.setPreferredSize(new java.awt.Dimension(130, 30));
        top_panel.add(home_page);
        home_page.setBounds(230, 60, 130, 30);

        order_history.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        order_history.setForeground(new java.awt.Color(255, 255, 255));
        order_history.setText("Order History");
        order_history.setAlignmentY(0.0F);
        order_history.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        order_history.setIconTextGap(0);
        order_history.setMaximumSize(new java.awt.Dimension(130, 30));
        order_history.setMinimumSize(new java.awt.Dimension(130, 30));
        order_history.setName(""); // NOI18N
        order_history.setPreferredSize(new java.awt.Dimension(130, 30));
        top_panel.add(order_history);
        order_history.setBounds(420, 60, 150, 30);

        e_wallet.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        e_wallet.setForeground(new java.awt.Color(255, 255, 255));
        e_wallet.setText("E-Wallet");
        e_wallet.setAlignmentY(0.0F);
        e_wallet.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        e_wallet.setIconTextGap(0);
        e_wallet.setMaximumSize(new java.awt.Dimension(130, 30));
        e_wallet.setMinimumSize(new java.awt.Dimension(130, 30));
        e_wallet.setName(""); // NOI18N
        e_wallet.setPreferredSize(new java.awt.Dimension(130, 30));
        top_panel.add(e_wallet);
        e_wallet.setBounds(620, 60, 150, 30);

        issue_and_support.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        issue_and_support.setForeground(new java.awt.Color(255, 255, 255));
        issue_and_support.setText("Issue and Support");
        issue_and_support.setAlignmentY(0.0F);
        issue_and_support.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        issue_and_support.setIconTextGap(0);
        issue_and_support.setMaximumSize(new java.awt.Dimension(130, 30));
        issue_and_support.setMinimumSize(new java.awt.Dimension(130, 30));
        issue_and_support.setName(""); // NOI18N
        issue_and_support.setPreferredSize(new java.awt.Dimension(130, 30));
        top_panel.add(issue_and_support);
        issue_and_support.setBounds(770, 60, 210, 30);

        welcome_text.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        welcome_text.setForeground(new java.awt.Color(255, 255, 255));
        welcome_text.setText("Welcome, ");
        welcome_text.setAlignmentY(0.0F);
        welcome_text.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        welcome_text.setIconTextGap(0);
        welcome_text.setMaximumSize(new java.awt.Dimension(130, 30));
        welcome_text.setMinimumSize(new java.awt.Dimension(130, 30));
        welcome_text.setName(""); // NOI18N
        welcome_text.setPreferredSize(new java.awt.Dimension(130, 30));
        top_panel.add(welcome_text);
        welcome_text.setBounds(70, 140, 130, 30);

        settings_icon.setBackground(new java.awt.Color(255, 255, 255));
        settings_icon.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        settings_icon.setForeground(new java.awt.Color(255, 255, 255));
        settings_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/system/settings.png"))); // NOI18N
        settings_icon.setAlignmentY(0.0F);
        settings_icon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        settings_icon.setIconTextGap(0);
        settings_icon.setMaximumSize(new java.awt.Dimension(130, 30));
        settings_icon.setMinimumSize(new java.awt.Dimension(130, 30));
        settings_icon.setName(""); // NOI18N
        settings_icon.setPreferredSize(new java.awt.Dimension(130, 30));
        top_panel.add(settings_icon);
        settings_icon.setBounds(1100, 40, 60, 70);

        notification_icon.setBackground(new java.awt.Color(255, 255, 255));
        notification_icon.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        notification_icon.setForeground(new java.awt.Color(255, 255, 255));
        notification_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/system/notification_icon.png"))); // NOI18N
        notification_icon.setAlignmentY(0.0F);
        notification_icon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        notification_icon.setIconTextGap(0);
        notification_icon.setMaximumSize(new java.awt.Dimension(130, 30));
        notification_icon.setMinimumSize(new java.awt.Dimension(130, 30));
        notification_icon.setName(""); // NOI18N
        notification_icon.setPreferredSize(new java.awt.Dimension(130, 30));
        top_panel.add(notification_icon);
        notification_icon.setBounds(1200, 30, 60, 70);

        back_icon.setBackground(new java.awt.Color(255, 255, 255));
        back_icon.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        back_icon.setForeground(new java.awt.Color(255, 255, 255));
        back_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/system/logout_icon.png"))); // NOI18N
        back_icon.setAlignmentY(0.0F);
        back_icon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        back_icon.setIconTextGap(0);
        back_icon.setMaximumSize(new java.awt.Dimension(130, 30));
        back_icon.setMinimumSize(new java.awt.Dimension(130, 30));
        back_icon.setName(""); // NOI18N
        back_icon.setPreferredSize(new java.awt.Dimension(130, 30));
        top_panel.add(back_icon);
        back_icon.setBounds(1290, 40, 60, 70);

        customer_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/system/darked_customer_background.jpg"))); // NOI18N
        customer_background.setText("jLabel1");
        top_panel.add(customer_background);
        customer_background.setBounds(0, 0, 1540, 690);

        getContentPane().add(top_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1452, 200));

        bottom_panel.setBackground(new java.awt.Color(255, 251, 233));
        bottom_panel.setAlignmentX(0.0F);
        bottom_panel.setAlignmentY(0.0F);
        bottom_panel.setPreferredSize(new java.awt.Dimension(1400, 600));
        bottom_panel.setLayout(null);

        current_orders_text.setBackground(new java.awt.Color(0, 0, 0));
        current_orders_text.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        current_orders_text.setForeground(new java.awt.Color(0, 0, 0));
        current_orders_text.setText("Current Orders");
        bottom_panel.add(current_orders_text);
        current_orders_text.setBounds(30, 19, 650, 48);
        bottom_panel.add(current_orders_panel);
        current_orders_panel.setBounds(30, 73, 650, 450);

        current_orders_text1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        current_orders_text1.setForeground(new java.awt.Color(0, 0, 0));
        current_orders_text1.setText("Categories");
        bottom_panel.add(current_orders_text1);
        current_orders_text1.setBounds(700, 20, 650, 48);
        bottom_panel.add(categories_panel);
        categories_panel.setBounds(700, 70, 650, 450);

        getContentPane().add(bottom_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerHomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back_icon;
    private javax.swing.JPanel bottom_panel;
    private javax.swing.JScrollPane categories_panel;
    private javax.swing.JScrollPane current_orders_panel;
    private javax.swing.JLabel current_orders_text;
    private javax.swing.JLabel current_orders_text1;
    private javax.swing.JLabel customer_background;
    private javax.swing.JLabel e_wallet;
    private javax.swing.JLabel home_page;
    private javax.swing.JLabel issue_and_support;
    private javax.swing.JLabel logo_light;
    private javax.swing.JLabel notification_icon;
    private javax.swing.JLabel order_history;
    private javax.swing.JLabel settings_icon;
    public javax.swing.JPanel top_panel;
    private javax.swing.JLabel welcome_text;
    // End of variables declaration//GEN-END:variables
}
