/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frontend.customer;

import backend.entity.Feedback;
import backend.file_io.PictureIO;
import backend.utility.Utility;
import java.io.File;
import javax.swing.ImageIcon;

/**
 *
 * @author Jun Hong (TP068580), Beng Rhui (TP068495)
 */
public class FeedbackBriefPanel extends javax.swing.JPanel {

    private Feedback currentFeedback;
    
    /**
     * Creates new form FeedbackBriefPanel
     */
    public FeedbackBriefPanel(Feedback feedback) {
        
        // Initialize the feedback
        currentFeedback = feedback;
        
        // Render GUI components
        initComponents();
        
        // Retrieve the icons
        File[] directory = new File(PictureIO.PARENT_PATH_TO_SYSTEM_DIRECTORY).listFiles();
        File pendingReviewFile = Utility.retrieveFileWithoutExtension(directory, "pending_review_icon");
        File managerReviewedFile = Utility.retrieveFileWithoutExtension(directory, "manager_review_icon");
        ImageIcon pendingReviewIcon = new ImageIcon(pendingReviewFile.getAbsolutePath());
        ImageIcon managerReviewIcon = new ImageIcon(managerReviewedFile.getAbsolutePath());
        
        // Update the panel based on category
        if (currentFeedback.getReplyFromManager() != null) statusIcon.setIcon(managerReviewIcon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        statusIcon = new javax.swing.JLabel();
        titleScrollPane = new javax.swing.JScrollPane();
        titleField = new javax.swing.JTextArea();
        viewIcon = new javax.swing.JLabel();
        categoryField = new javax.swing.JLabel();

        setBackground(new java.awt.Color(227, 202, 165));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setPreferredSize(new java.awt.Dimension(610, 135));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        statusIcon.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        statusIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        statusIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/system/pending_review_icon.png"))); // NOI18N
        add(statusIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 50, 50));

        titleScrollPane.setBorder(null);

        titleField.setEditable(false);
        titleField.setBackground(new java.awt.Color(227, 202, 165));
        titleField.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        titleField.setRows(1);
        titleField.setText(currentFeedback.getFeedbackTitle());
        titleField.setBorder(null);
        titleScrollPane.setViewportView(titleField);

        add(titleScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 440, 30));

        viewIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viewIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/system/search_icon.png"))); // NOI18N
        add(viewIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 50, 70));

        categoryField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        categoryField.setText("Category: " + currentFeedback.getFeedbackCategory());
        add(categoryField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 420, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked

        // Disable the main parent
        MainPage.currentFrame.setEnabled(false);
        
        // Call the feedback details form
        FeedbackDetailsFrame feedbackDetails = new FeedbackDetailsFrame(currentFeedback);
        feedbackDetails.setLocationRelativeTo(MainPage.currentFrame);
        feedbackDetails.setVisible(true);
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel categoryField;
    private javax.swing.JLabel statusIcon;
    private javax.swing.JTextArea titleField;
    private javax.swing.JScrollPane titleScrollPane;
    private javax.swing.JLabel viewIcon;
    // End of variables declaration//GEN-END:variables
}
