/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frontend.customer;

import backend.entity.Order;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Jun Hong (TP068580), Beng Rhui (TP068495)
 */
public class OrderHistoryPanel extends javax.swing.JPanel {

    /**
     * Creates new form OrderHistoryPanel
     */
    public OrderHistoryPanel() {
        
        // Render GUI components
        initComponents();
        
        // Initialize the order history panel
        updateOrderHistoryPanel();
    }

    /**
     * This method helps to update the order history panel.
     */
    public static void updateOrderHistoryPanel() {
    
        // Remove everything on the panel
        orderHistoryPanel.removeAll();
        
        // Retrieve the list of completed orders
        ArrayList<Order> orderList = Order.getCompleteOrders(MainPage.getCustomer());
        
        // If there is no vendor
        if (orderList.isEmpty()) {
        
            // Create a JLabel and JPanel to display message
            JPanel emptyPanel = new JPanel(null);
            JLabel emptyLabel = new JLabel("No order history available.");
            
            // Set attributes to the label
            emptyLabel.setFont(new Font("Arial", Font.PLAIN, 24));
            emptyLabel.setBounds(0, 0, 500, 30);
            
            // Add label to panel
            emptyPanel.add(emptyLabel);
            emptyPanel.setBackground(new Color(255, 251, 233));
            
            // Add panel to the container
            orderHistoryPanel.add(emptyPanel);
            
        } else {
        
            // Loop through vendor list
            for (Order order : orderList) {

                // Create panel to show vendor information
                JPanel panel = new OrderHistoryBriefPanel(order);
                orderHistoryPanel.add(panel);
            }
            
            // Add empty panels if the number of vendors is not sufficient
            for (int i = orderList.size() + 1; i < 7; i ++) {
                
                // Create empty panels
                JPanel emptyPanel = new JPanel();
                
                // Set background
                emptyPanel.setBackground(new Color(255, 251, 233));
                
                // Add the empty panel to container
                orderHistoryPanel.add(emptyPanel);
            }
        }
        
        // Refresh panel
        orderHistoryPanel.revalidate();
        orderHistoryPanel.repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        orderHistoryScrollPane = new javax.swing.JScrollPane();
        orderHistoryPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 251, 233));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        orderHistoryScrollPane.setBorder(null);
        orderHistoryScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        orderHistoryScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        orderHistoryPanel.setBackground(new java.awt.Color(255, 251, 233));
        orderHistoryPanel.setLayout(new java.awt.GridLayout(0, 3, 10, 10));
        orderHistoryScrollPane.setViewportView(orderHistoryPanel);

        add(orderHistoryScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 1280, 450));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JPanel orderHistoryPanel;
    private javax.swing.JScrollPane orderHistoryScrollPane;
    // End of variables declaration//GEN-END:variables
}
