/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frontend.Customer;

/**
 *
 * @author Lenovo
 */
public class PopUpDigitalReceipt extends javax.swing.JPanel {

    /**
     * Creates new form PopUpCheckPreviousOrder
     */
    public PopUpDigitalReceipt() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        receipt_text = new javax.swing.JLabel();
        description_text = new javax.swing.JLabel();
        description_detail = new javax.swing.JPanel();
        quantity_text = new javax.swing.JLabel();
        quantity_detail = new javax.swing.JPanel();
        price_text = new javax.swing.JLabel();
        price_detail = new javax.swing.JPanel();
        total_amount_text = new javax.swing.JLabel();
        total_amount_rm = new javax.swing.JLabel();
        total_amount_value = new javax.swing.JTextArea();
        receipt_reference_text = new javax.swing.JLabel();
        receipt_reference_input = new javax.swing.JTextField();
        date_time_text = new javax.swing.JLabel();
        date_time_input = new javax.swing.JTextField();
        payment_method_text = new javax.swing.JLabel();
        payment_method_input = new javax.swing.JTextField();
        print_button = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 251, 233));
        setPreferredSize(new java.awt.Dimension(1400, 800));
        setLayout(null);

        receipt_text.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        receipt_text.setForeground(new java.awt.Color(0, 0, 0));
        receipt_text.setText("Receipt");
        add(receipt_text);
        receipt_text.setBounds(110, 42, 174, 56);

        description_text.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        description_text.setForeground(new java.awt.Color(0, 0, 0));
        description_text.setText("Description");
        add(description_text);
        description_text.setBounds(110, 150, 220, 42);

        description_detail.setBackground(new java.awt.Color(255, 251, 233));
        description_detail.setPreferredSize(new java.awt.Dimension(470, 520));

        javax.swing.GroupLayout description_detailLayout = new javax.swing.GroupLayout(description_detail);
        description_detail.setLayout(description_detailLayout);
        description_detailLayout.setHorizontalGroup(
            description_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );
        description_detailLayout.setVerticalGroup(
            description_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        add(description_detail);
        description_detail.setBounds(110, 220, 470, 450);

        quantity_text.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        quantity_text.setForeground(new java.awt.Color(0, 0, 0));
        quantity_text.setText("Quantity");
        add(quantity_text);
        quantity_text.setBounds(590, 150, 180, 42);

        quantity_detail.setBackground(new java.awt.Color(255, 251, 233));
        quantity_detail.setPreferredSize(new java.awt.Dimension(470, 520));

        javax.swing.GroupLayout quantity_detailLayout = new javax.swing.GroupLayout(quantity_detail);
        quantity_detail.setLayout(quantity_detailLayout);
        quantity_detailLayout.setHorizontalGroup(
            quantity_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );
        quantity_detailLayout.setVerticalGroup(
            quantity_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        add(quantity_detail);
        quantity_detail.setBounds(574, 220, 190, 450);

        price_text.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        price_text.setForeground(new java.awt.Color(0, 0, 0));
        price_text.setText("Price");
        add(price_text);
        price_text.setBounds(820, 150, 150, 42);

        price_detail.setBackground(new java.awt.Color(255, 251, 233));
        price_detail.setPreferredSize(new java.awt.Dimension(470, 520));

        javax.swing.GroupLayout price_detailLayout = new javax.swing.GroupLayout(price_detail);
        price_detail.setLayout(price_detailLayout);
        price_detailLayout.setHorizontalGroup(
            price_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        price_detailLayout.setVerticalGroup(
            price_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        add(price_detail);
        price_detail.setBounds(764, 220, 200, 450);

        total_amount_text.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        total_amount_text.setForeground(new java.awt.Color(0, 0, 0));
        total_amount_text.setText("Total Amount");
        add(total_amount_text);
        total_amount_text.setBounds(110, 713, 156, 28);

        total_amount_rm.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        total_amount_rm.setForeground(new java.awt.Color(0, 0, 0));
        total_amount_rm.setText("RM");
        add(total_amount_rm);
        total_amount_rm.setBounds(740, 710, 38, 28);

        total_amount_value.setBackground(new java.awt.Color(255, 251, 233));
        total_amount_value.setColumns(1);
        total_amount_value.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        total_amount_value.setForeground(new java.awt.Color(0, 0, 0));
        total_amount_value.setRows(1);
        total_amount_value.setText("123, 123");
        add(total_amount_value);
        total_amount_value.setBounds(786, 707, 170, 30);

        receipt_reference_text.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        receipt_reference_text.setForeground(new java.awt.Color(0, 0, 0));
        receipt_reference_text.setText("Receipt Reference");
        add(receipt_reference_text);
        receipt_reference_text.setBounds(1000, 150, 330, 42);

        receipt_reference_input.setBackground(new java.awt.Color(255, 251, 233));
        receipt_reference_input.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        receipt_reference_input.setForeground(new java.awt.Color(0, 0, 0));
        receipt_reference_input.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        receipt_reference_input.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        add(receipt_reference_input);
        receipt_reference_input.setBounds(1000, 200, 320, 60);

        date_time_text.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        date_time_text.setForeground(new java.awt.Color(0, 0, 0));
        date_time_text.setText("Date / Time");
        add(date_time_text);
        date_time_text.setBounds(1000, 320, 220, 42);

        date_time_input.setBackground(new java.awt.Color(255, 251, 233));
        date_time_input.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        date_time_input.setForeground(new java.awt.Color(0, 0, 0));
        date_time_input.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        date_time_input.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        add(date_time_input);
        date_time_input.setBounds(1000, 370, 330, 60);

        payment_method_text.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        payment_method_text.setForeground(new java.awt.Color(0, 0, 0));
        payment_method_text.setText("Payment Method");
        add(payment_method_text);
        payment_method_text.setBounds(1000, 490, 310, 42);

        payment_method_input.setBackground(new java.awt.Color(255, 251, 233));
        payment_method_input.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        payment_method_input.setForeground(new java.awt.Color(0, 0, 0));
        payment_method_input.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        payment_method_input.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        add(payment_method_input);
        payment_method_input.setBounds(1000, 540, 340, 60);

        print_button.setBackground(new java.awt.Color(173, 139, 115));
        print_button.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        print_button.setForeground(new java.awt.Color(255, 255, 255));
        print_button.setText("Print");
        print_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                print_buttonActionPerformed(evt);
            }
        });
        add(print_button);
        print_button.setBounds(1000, 690, 275, 60);
    }// </editor-fold>//GEN-END:initComponents

    private void print_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_print_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_print_buttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField date_time_input;
    private javax.swing.JLabel date_time_text;
    private javax.swing.JPanel description_detail;
    private javax.swing.JLabel description_text;
    private javax.swing.JTextField payment_method_input;
    private javax.swing.JLabel payment_method_text;
    private javax.swing.JPanel price_detail;
    private javax.swing.JLabel price_text;
    private javax.swing.JButton print_button;
    private javax.swing.JPanel quantity_detail;
    private javax.swing.JLabel quantity_text;
    private javax.swing.JTextField receipt_reference_input;
    private javax.swing.JLabel receipt_reference_text;
    private javax.swing.JLabel receipt_text;
    private javax.swing.JLabel total_amount_rm;
    private javax.swing.JLabel total_amount_text;
    private javax.swing.JTextArea total_amount_value;
    // End of variables declaration//GEN-END:variables
}
