/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frontend.customer;

import backend.entity.Transaction;
import backend.utility.Utility;

/**
 *
 * @author Jun Hong (TP068580), Beng Rhui (TP068495)
 */
public class TransactionBriefPanel extends javax.swing.JPanel {

    private Transaction currentTransaction;
    
    /**
     * Creates new form transactionBriefPanel
     */
    public TransactionBriefPanel(Transaction transaction) {
        
        // Retrieve the current transaction
        currentTransaction = transaction;
        
        // Render GUI components
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        timeField = new javax.swing.JLabel();
        descriptionField = new javax.swing.JLabel();
        transactionIcon = new javax.swing.JLabel();

        setBackground(new java.awt.Color(227, 202, 165));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        setPreferredSize(new java.awt.Dimension(420, 110));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        timeField.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        timeField.setText(Utility.generateString(currentTransaction.getTransactionTime()));
        add(timeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 250, 40));

        descriptionField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        descriptionField.setText(String.format(
            "%s RM%.2f %s account.",
            currentTransaction.getTransactionType().toString().substring(0, 1).toUpperCase() + currentTransaction.getTransactionType().toString().substring(1).toLowerCase(),
            currentTransaction.getTransactionAmount(),
            currentTransaction.getTransactionType() == Transaction.TransactionType.CASH_IN ? "into" : "from"
        )
    );
    add(descriptionField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 290, 30));

    transactionIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    transactionIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/system/transaction_icon.png"))); // NOI18N
    transactionIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    transactionIcon.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            transactionIconMouseClicked(evt);
        }
    });
    add(transactionIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 80, 70));
    }// </editor-fold>//GEN-END:initComponents

    private void transactionIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transactionIconMouseClicked
        
        // Disable the main frame
        MainPage.currentFrame.setEnabled(false);
        
        // Display the receipt pop up
        TransactionReceiptPopUp receiptPopUp = new TransactionReceiptPopUp(currentTransaction);
        receiptPopUp.setLocationRelativeTo(MainPage.currentFrame);
        receiptPopUp.setVisible(true);
    }//GEN-LAST:event_transactionIconMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel descriptionField;
    private javax.swing.JLabel timeField;
    private javax.swing.JLabel transactionIcon;
    // End of variables declaration//GEN-END:variables
}
