/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package frontend.pop_up;

import java.awt.Color;
import javax.swing.JFrame;

/**
 *
 * @author Beng Rhui (TP068495)
 */
public class TableNumberPopUp extends javax.swing.JDialog {

    private static JFrame parentFrame;
    private static String tableNumber;
    public int status;
    
    /**
     * Creates new form TableNumberPopUp
     */
    public TableNumberPopUp(JFrame parent, String inputTableNumber) {
        
        // Call parent constructor
        super(parent, true);
        
        // Set the parent frame
        parentFrame = parent;
        
        // Update table number
        if (inputTableNumber != null) tableNumber = inputTableNumber.toUpperCase();
        else tableNumber = null;
        
        // Render GUI components
        initComponents();
        
        // If table number is not null, then set text colour to black
        if (inputTableNumber != null) tableNumberField.setForeground(Color.BLACK);
    }

    /**
     * This method helps to retrieve the table number inputted by user.
     * @return The inputted table number
     */
    public String retrieveTableNumber() {
        return tableNumber;
    }
    
    public void removeCancelButton() {
        backgroundPanel.remove(cancelButton);
        confirmButton.setBounds(50, 200, 300, 50);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        tableNumberTitle = new javax.swing.JLabel();
        tableNumberField = new javax.swing.JTextField();
        cancelButton = new javax.swing.JButton();
        confirmButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backgroundPanel.setBackground(new java.awt.Color(255, 251, 233));
        backgroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableNumberTitle.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        tableNumberTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tableNumberTitle.setText("Table Number");
        backgroundPanel.add(tableNumberTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 300, -1));

        tableNumberField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tableNumberField.setForeground(new java.awt.Color(204, 204, 204));
        tableNumberField.setText(tableNumber == null ? "Enter Table Number" : tableNumber);
        tableNumberField.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), javax.swing.BorderFactory.createEmptyBorder(2, 15, 2, 15)));
        tableNumberField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tableNumberFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tableNumberFieldFocusLost(evt);
            }
        });
        backgroundPanel.add(tableNumberField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 300, 60));

        cancelButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        cancelButton.setFocusPainted(false);
        cancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancelButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelButtonMouseExited(evt);
            }
        });
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        backgroundPanel.add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 140, 50));

        confirmButton.setBackground(new java.awt.Color(0, 0, 0));
        confirmButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        confirmButton.setForeground(new java.awt.Color(255, 255, 255));
        confirmButton.setText("OK");
        confirmButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        confirmButton.setFocusPainted(false);
        confirmButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                confirmButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                confirmButtonMouseExited(evt);
            }
        });
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });
        backgroundPanel.add(confirmButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 140, 50));

        getContentPane().add(backgroundPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed

        // Enable the parent frame
        parentFrame.setEnabled(true);
        
        // Set status to 0
        status = 0;
        
        // Dispose the current frame
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed

        // Retrieve information
        String inputTableNumber = tableNumberField.getText().toUpperCase().strip().replace(" ", "");
        
        // Only perform action if the input is not blank
        if (!inputTableNumber.equalsIgnoreCase("ENTERTABLENUMBER")) {
            
            // Set the table number
            tableNumber = inputTableNumber;

            // Enable the parent frame
            parentFrame.setEnabled(true);

            // Set status to 1
            status = 1;
            
            // Dispose the current frame
            dispose();
        }
    }//GEN-LAST:event_confirmButtonActionPerformed

    private void cancelButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonMouseEntered

        // Change background
        cancelButton.setBackground(new Color(206, 171, 147));
    }//GEN-LAST:event_cancelButtonMouseEntered

    private void cancelButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonMouseExited

        // Change background
        cancelButton.setBackground(Color.WHITE);
    }//GEN-LAST:event_cancelButtonMouseExited

    private void confirmButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmButtonMouseEntered

        // Change background and text
        confirmButton.setBackground(new Color(206, 171, 147));
        confirmButton.setForeground(Color.BLACK);
    }//GEN-LAST:event_confirmButtonMouseEntered

    private void confirmButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmButtonMouseExited

        // Change background and text
        confirmButton.setBackground(Color.BLACK);
        confirmButton.setForeground(Color.WHITE);
    }//GEN-LAST:event_confirmButtonMouseExited

    private void tableNumberFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tableNumberFieldFocusGained

        // If the prompt is still there
        if (tableNumberField.getText().equals("Enter Table Number")) {
            
            // Remove the prompt
            tableNumberField.setText("");
            
            // Change text to black
            tableNumberField.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_tableNumberFieldFocusGained

    private void tableNumberFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tableNumberFieldFocusLost

        // If the input is blank
        if (tableNumberField.getText().isBlank()) {
            
            // Remove the prompt
            tableNumberField.setText("Enter Table Number");
            
            // Change text to grey
            tableNumberField.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_tableNumberFieldFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TableNumberPopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TableNumberPopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TableNumberPopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TableNumberPopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TableNumberPopUp dialog = new TableNumberPopUp(new javax.swing.JFrame(), "T001");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton confirmButton;
    private javax.swing.JTextField tableNumberField;
    private javax.swing.JLabel tableNumberTitle;
    // End of variables declaration//GEN-END:variables
}
