/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend.Runner;

/**
 *
 * @author Lenovo
 */
public class RunnerDeliverHistory extends javax.swing.JFrame {

    /**
     * Creates new form RunnerMain
     */
    public RunnerDeliverHistory() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        top_panel = new javax.swing.JPanel();
        home_page = new javax.swing.JButton();
        delivery_history = new javax.swing.JButton();
        logo_light = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        back1 = new javax.swing.JLabel();
        bottom_panel = new javax.swing.JPanel();
        revenue_text = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        daily_button = new javax.swing.JButton();
        monthly_button = new javax.swing.JButton();
        quarterly_button = new javax.swing.JButton();
        yearly_button = new javax.swing.JButton();
        total_delivery_text = new javax.swing.JLabel();
        total_earnings_text = new javax.swing.JLabel();
        total_delivery_value = new javax.swing.JTextField();
        total_earnings_value = new javax.swing.JTextField();
        recent_delivery_text = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1400, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        top_panel.setBackground(new java.awt.Color(102, 102, 102));
        top_panel.setPreferredSize(new java.awt.Dimension(1400, 140));

        home_page.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        home_page.setText("Home Page");
        home_page.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home_pageActionPerformed(evt);
            }
        });

        delivery_history.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        delivery_history.setText("Delivery History");
        delivery_history.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delivery_historyActionPerformed(evt);
            }
        });

        logo_light.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo_light.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/system/logo_light.png"))); // NOI18N
        logo_light.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        logo_light.setMaximumSize(new java.awt.Dimension(120, 120));
        logo_light.setMinimumSize(new java.awt.Dimension(120, 120));
        logo_light.setPreferredSize(new java.awt.Dimension(100, 100));
        logo_light.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                logo_lightComponentResized(evt);
            }
        });

        back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/system/logout_icon.png"))); // NOI18N
        back.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        back.setMaximumSize(new java.awt.Dimension(120, 120));
        back.setMinimumSize(new java.awt.Dimension(120, 120));
        back.setPreferredSize(new java.awt.Dimension(80, 80));
        back.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                backComponentResized(evt);
            }
        });

        back1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/system/notification_icon.png"))); // NOI18N
        back1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        back1.setMaximumSize(new java.awt.Dimension(120, 120));
        back1.setMinimumSize(new java.awt.Dimension(120, 120));
        back1.setPreferredSize(new java.awt.Dimension(80, 80));
        back1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                back1ComponentResized(evt);
            }
        });

        javax.swing.GroupLayout top_panelLayout = new javax.swing.GroupLayout(top_panel);
        top_panel.setLayout(top_panelLayout);
        top_panelLayout.setHorizontalGroup(
            top_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(top_panelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(logo_light, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(home_page, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(delivery_history, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 639, Short.MAX_VALUE)
                .addComponent(back1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        top_panelLayout.setVerticalGroup(
            top_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(top_panelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(top_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(home_page, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delivery_history, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logo_light, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(back1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        getContentPane().add(top_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        bottom_panel.setBackground(new java.awt.Color(204, 204, 204));
        bottom_panel.setPreferredSize(new java.awt.Dimension(1400, 640));

        revenue_text.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        revenue_text.setText("Revenue");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        daily_button.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        daily_button.setText("Daily");
        daily_button.setAlignmentY(0.0F);
        daily_button.setIconTextGap(0);
        daily_button.setMargin(new java.awt.Insets(0, 0, 0, 0));
        daily_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daily_buttonActionPerformed(evt);
            }
        });

        monthly_button.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        monthly_button.setText("Monthly");
        monthly_button.setAlignmentY(0.0F);
        monthly_button.setIconTextGap(0);
        monthly_button.setMargin(new java.awt.Insets(0, 0, 0, 0));
        monthly_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthly_buttonActionPerformed(evt);
            }
        });

        quarterly_button.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        quarterly_button.setText("Quarterly");
        quarterly_button.setAlignmentY(0.0F);
        quarterly_button.setIconTextGap(0);
        quarterly_button.setMargin(new java.awt.Insets(0, 0, 0, 0));
        quarterly_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quarterly_buttonActionPerformed(evt);
            }
        });

        yearly_button.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        yearly_button.setText("Yearly");
        yearly_button.setAlignmentY(0.0F);
        yearly_button.setIconTextGap(0);
        yearly_button.setMargin(new java.awt.Insets(0, 0, 0, 0));
        yearly_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearly_buttonActionPerformed(evt);
            }
        });

        total_delivery_text.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        total_delivery_text.setText("Total Delivery");

        total_earnings_text.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        total_earnings_text.setText("Total Earnings");

        total_delivery_value.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        total_delivery_value.setText("123,123");
        total_delivery_value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total_delivery_valueActionPerformed(evt);
            }
        });

        total_earnings_value.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        total_earnings_value.setText("RM 123,123");
        total_earnings_value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total_earnings_valueActionPerformed(evt);
            }
        });

        recent_delivery_text.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        recent_delivery_text.setText("Recent Delivery");

        javax.swing.GroupLayout bottom_panelLayout = new javax.swing.GroupLayout(bottom_panel);
        bottom_panel.setLayout(bottom_panelLayout);
        bottom_panelLayout.setHorizontalGroup(
            bottom_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottom_panelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(bottom_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(revenue_text))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(bottom_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bottom_panelLayout.createSequentialGroup()
                        .addComponent(daily_button, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(monthly_button, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(quarterly_button, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(yearly_button, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bottom_panelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(bottom_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bottom_panelLayout.createSequentialGroup()
                                .addGroup(bottom_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(total_delivery_value, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(total_delivery_text))
                                .addGap(58, 58, 58)
                                .addGroup(bottom_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(total_earnings_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(total_earnings_text)))
                            .addComponent(recent_delivery_text)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );
        bottom_panelLayout.setVerticalGroup(
            bottom_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottom_panelLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(revenue_text)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bottom_panelLayout.createSequentialGroup()
                .addGroup(bottom_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(daily_button, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(monthly_button, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quarterly_button, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearly_button, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(bottom_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(total_delivery_text)
                    .addComponent(total_earnings_text))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bottom_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(total_delivery_value, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(total_earnings_value, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(recent_delivery_text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        getContentPane().add(bottom_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, -1, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_backComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_backComponentResized

    private void delivery_historyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delivery_historyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_delivery_historyActionPerformed

    private void home_pageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home_pageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_home_pageActionPerformed

    private void logo_lightComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_logo_lightComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_logo_lightComponentResized

    private void back1ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_back1ComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_back1ComponentResized

    private void daily_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daily_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_daily_buttonActionPerformed

    private void monthly_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthly_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monthly_buttonActionPerformed

    private void quarterly_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quarterly_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quarterly_buttonActionPerformed

    private void yearly_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearly_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearly_buttonActionPerformed

    private void total_delivery_valueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total_delivery_valueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_total_delivery_valueActionPerformed

    private void total_earnings_valueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total_earnings_valueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_total_earnings_valueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RunnerDeliverHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RunnerDeliverHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RunnerDeliverHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RunnerDeliverHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RunnerDeliverHistory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JLabel back1;
    private javax.swing.JPanel bottom_panel;
    private javax.swing.JButton daily_button;
    private javax.swing.JButton delivery_history;
    private javax.swing.JButton home_page;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logo_light;
    private javax.swing.JButton monthly_button;
    private javax.swing.JButton quarterly_button;
    private javax.swing.JLabel recent_delivery_text;
    private javax.swing.JLabel revenue_text;
    private javax.swing.JPanel top_panel;
    private javax.swing.JLabel total_delivery_text;
    private javax.swing.JTextField total_delivery_value;
    private javax.swing.JLabel total_earnings_text;
    private javax.swing.JTextField total_earnings_value;
    private javax.swing.JButton yearly_button;
    // End of variables declaration//GEN-END:variables
}
