/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend.Runner;

/**
 *
 * @author Lenovo
 */
public class RunnerMain extends javax.swing.JFrame {

    /**
     * Creates new form RunnerMain
     */

    public RunnerMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        top_panel = new javax.swing.JPanel();
        logo_light = new javax.swing.JLabel();
        delivery_history = new javax.swing.JLabel();
        home_page = new javax.swing.JLabel();
        rating_icon = new javax.swing.JLabel();
        notification = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        runner_background = new javax.swing.JLabel();
        bottom_panel = new javax.swing.JPanel();
        current_task_text = new javax.swing.JLabel();
        current_task = new javax.swing.JPanel();
        buttom_top_panel = new javax.swing.JPanel();
        order_icon = new javax.swing.JLabel();
        current_task_combobox = new javax.swing.JComboBox<>();
        buttom_buttom_panel = new javax.swing.JPanel();
        person_icon = new javax.swing.JLabel();
        address_text = new javax.swing.JLabel();
        delivery_note = new javax.swing.JLabel();
        food_icon = new javax.swing.JLabel();
        food_text = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1400, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        top_panel.setBackground(new java.awt.Color(102, 102, 102));
        top_panel.setPreferredSize(new java.awt.Dimension(1400, 140));
        top_panel.setLayout(null);

        logo_light.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        logo_light.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo_light.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/system/logo_light.png"))); // NOI18N
        top_panel.add(logo_light);
        logo_light.setBounds(10, 0, 210, 130);

        delivery_history.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        delivery_history.setForeground(new java.awt.Color(255, 255, 255));
        delivery_history.setText("Delivery History");
        top_panel.add(delivery_history);
        delivery_history.setBounds(440, 50, 170, 28);

        home_page.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        home_page.setForeground(new java.awt.Color(255, 255, 255));
        home_page.setText("Home Page");
        top_panel.add(home_page);
        home_page.setBounds(240, 50, 130, 28);

        rating_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rating_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/system/rating_icon.png"))); // NOI18N
        rating_icon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rating_icon.setMaximumSize(new java.awt.Dimension(120, 120));
        rating_icon.setMinimumSize(new java.awt.Dimension(120, 120));
        rating_icon.setPreferredSize(new java.awt.Dimension(80, 80));
        rating_icon.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                rating_iconComponentResized(evt);
            }
        });
        top_panel.add(rating_icon);
        rating_icon.setBounds(1150, 30, 60, 70);

        notification.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        notification.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/system/notification_icon.png"))); // NOI18N
        notification.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        notification.setMaximumSize(new java.awt.Dimension(120, 120));
        notification.setMinimumSize(new java.awt.Dimension(120, 120));
        notification.setPreferredSize(new java.awt.Dimension(80, 80));
        notification.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                notificationComponentResized(evt);
            }
        });
        top_panel.add(notification);
        notification.setBounds(1230, 30, 60, 60);

        back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/system/logout_icon.png"))); // NOI18N
        back.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        back.setMaximumSize(new java.awt.Dimension(120, 120));
        back.setMinimumSize(new java.awt.Dimension(120, 120));
        back.setPreferredSize(new java.awt.Dimension(80, 80));
        back.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                backComponentResized(evt);
            }
        });
        top_panel.add(back);
        back.setBounds(1309, 39, 60, 60);

        runner_background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        runner_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/system/darken_runner_background.png"))); // NOI18N
        runner_background.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        runner_background.setMaximumSize(new java.awt.Dimension(120, 120));
        runner_background.setMinimumSize(new java.awt.Dimension(120, 120));
        runner_background.setPreferredSize(new java.awt.Dimension(80, 80));
        runner_background.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                runner_backgroundComponentResized(evt);
            }
        });
        top_panel.add(runner_background);
        runner_background.setBounds(0, 0, 1400, 700);

        getContentPane().add(top_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        bottom_panel.setBackground(new java.awt.Color(255, 251, 233));
        bottom_panel.setPreferredSize(new java.awt.Dimension(1400, 640));
        bottom_panel.setLayout(null);

        current_task_text.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        current_task_text.setForeground(new java.awt.Color(0, 0, 0));
        current_task_text.setText("Current Task");
        bottom_panel.add(current_task_text);
        current_task_text.setBounds(60, 45, 298, 56);

        current_task.setBackground(new java.awt.Color(255, 251, 233));
        current_task.setLayout(null);

        buttom_top_panel.setBackground(new java.awt.Color(227, 202, 165));
        buttom_top_panel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        order_icon.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        order_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        order_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/system/order_icon.png"))); // NOI18N

        current_task_combobox.setBackground(new java.awt.Color(255, 255, 255));
        current_task_combobox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        current_task_combobox.setForeground(new java.awt.Color(0, 0, 0));
        current_task_combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Preparing", "Done", "Out of Delivery" }));
        current_task_combobox.setPreferredSize(new java.awt.Dimension(300, 60));

        javax.swing.GroupLayout buttom_top_panelLayout = new javax.swing.GroupLayout(buttom_top_panel);
        buttom_top_panel.setLayout(buttom_top_panelLayout);
        buttom_top_panelLayout.setHorizontalGroup(
            buttom_top_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttom_top_panelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(order_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 794, Short.MAX_VALUE)
                .addComponent(current_task_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        buttom_top_panelLayout.setVerticalGroup(
            buttom_top_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttom_top_panelLayout.createSequentialGroup()
                .addGroup(buttom_top_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(buttom_top_panelLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(current_task_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(buttom_top_panelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(order_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );

        current_task.add(buttom_top_panel);
        buttom_top_panel.setBounds(0, 0, 1290, 130);

        buttom_buttom_panel.setBackground(new java.awt.Color(255, 255, 255));
        buttom_buttom_panel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        person_icon.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        person_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        person_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/system/person_icon.png"))); // NOI18N

        address_text.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        address_text.setForeground(new java.awt.Color(0, 0, 0));
        address_text.setText("Address");

        delivery_note.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        delivery_note.setForeground(new java.awt.Color(0, 0, 0));
        delivery_note.setText("Delivery Note");

        food_icon.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        food_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        food_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/system/food_icon.png"))); // NOI18N

        food_text.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        food_text.setForeground(new java.awt.Color(0, 0, 0));
        food_text.setText("Food");

        javax.swing.GroupLayout buttom_buttom_panelLayout = new javax.swing.GroupLayout(buttom_buttom_panel);
        buttom_buttom_panel.setLayout(buttom_buttom_panelLayout);
        buttom_buttom_panelLayout.setHorizontalGroup(
            buttom_buttom_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttom_buttom_panelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(food_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(food_text, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(214, 214, 214)
                .addComponent(person_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(615, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttom_buttom_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(buttom_buttom_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(delivery_note, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(address_text, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(340, 340, 340))
        );
        buttom_buttom_panelLayout.setVerticalGroup(
            buttom_buttom_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttom_buttom_panelLayout.createSequentialGroup()
                .addGroup(buttom_buttom_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(buttom_buttom_panelLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(buttom_buttom_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(person_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(food_icon)))
                    .addGroup(buttom_buttom_panelLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(food_text)))
                .addGap(44, 44, 44)
                .addComponent(address_text)
                .addGap(71, 71, 71)
                .addComponent(delivery_note)
                .addContainerGap(107, Short.MAX_VALUE))
        );

        current_task.add(buttom_buttom_panel);
        buttom_buttom_panel.setBounds(20, 100, 1250, 410);

        bottom_panel.add(current_task);
        current_task.setBounds(60, 120, 1300, 510);

        getContentPane().add(bottom_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, -1, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void notificationComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_notificationComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_notificationComponentResized

    private void runner_backgroundComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_runner_backgroundComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_runner_backgroundComponentResized

    private void backComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_backComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_backComponentResized

    private void rating_iconComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_rating_iconComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_rating_iconComponentResized

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RunnerMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RunnerMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RunnerMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RunnerMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RunnerMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel address_text;
    private javax.swing.JLabel back;
    private javax.swing.JPanel bottom_panel;
    private javax.swing.JPanel buttom_buttom_panel;
    private javax.swing.JPanel buttom_top_panel;
    private javax.swing.JPanel current_task;
    private javax.swing.JComboBox<String> current_task_combobox;
    private javax.swing.JLabel current_task_text;
    private javax.swing.JLabel delivery_history;
    private javax.swing.JLabel delivery_note;
    private javax.swing.JLabel food_icon;
    private javax.swing.JLabel food_text;
    private javax.swing.JLabel home_page;
    private javax.swing.JLabel logo_light;
    private javax.swing.JLabel notification;
    private javax.swing.JLabel order_icon;
    private javax.swing.JLabel person_icon;
    private javax.swing.JLabel rating_icon;
    private javax.swing.JLabel runner_background;
    private javax.swing.JPanel top_panel;
    // End of variables declaration//GEN-END:variables
}
