/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend.Runner;

/**
 *
 * @author Lenovo
 */
public class RunnerDeliverHistory extends javax.swing.JFrame {

    /**
     * Creates new form RunnerMain
     */
    public RunnerDeliverHistory() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        top_panel = new javax.swing.JPanel();
        logo_light = new javax.swing.JLabel();
        home_page = new javax.swing.JLabel();
        delivery_history = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        notification = new javax.swing.JLabel();
        rating_icon = new javax.swing.JLabel();
        runner_background = new javax.swing.JLabel();
        bottom_panel = new javax.swing.JPanel();
        revenue_text = new javax.swing.JLabel();
        graph_panel = new javax.swing.JPanel();
        daily_button = new javax.swing.JButton();
        monthly_button = new javax.swing.JButton();
        quarterly_button = new javax.swing.JButton();
        yearly_button = new javax.swing.JButton();
        total_delivery_text = new javax.swing.JLabel();
        total_earnings_text = new javax.swing.JLabel();
        total_delivery_value = new javax.swing.JTextField();
        total_earnings_value = new javax.swing.JTextField();
        recent_delivery_text = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1400, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        top_panel.setBackground(new java.awt.Color(102, 102, 102));
        top_panel.setPreferredSize(new java.awt.Dimension(1400, 140));
        top_panel.setLayout(null);

        logo_light.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo_light.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/system/logo_light.png"))); // NOI18N
        logo_light.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        logo_light.setMaximumSize(new java.awt.Dimension(120, 120));
        logo_light.setMinimumSize(new java.awt.Dimension(120, 120));
        logo_light.setPreferredSize(new java.awt.Dimension(100, 100));
        logo_light.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                logo_lightComponentResized(evt);
            }
        });
        top_panel.add(logo_light);
        logo_light.setBounds(10, 0, 210, 130);

        home_page.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        home_page.setForeground(new java.awt.Color(255, 255, 255));
        home_page.setText("Home Page");
        top_panel.add(home_page);
        home_page.setBounds(240, 50, 200, 28);

        delivery_history.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        delivery_history.setForeground(new java.awt.Color(255, 255, 255));
        delivery_history.setText("Delivery History");
        top_panel.add(delivery_history);
        delivery_history.setBounds(440, 50, 260, 28);

        back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/system/logout_icon.png"))); // NOI18N
        back.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        back.setMaximumSize(new java.awt.Dimension(120, 120));
        back.setMinimumSize(new java.awt.Dimension(120, 120));
        back.setPreferredSize(new java.awt.Dimension(80, 80));
        back.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                backComponentResized(evt);
            }
        });
        top_panel.add(back);
        back.setBounds(1309, 39, 60, 60);

        notification.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        notification.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/system/notification_icon.png"))); // NOI18N
        notification.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        notification.setMaximumSize(new java.awt.Dimension(120, 120));
        notification.setMinimumSize(new java.awt.Dimension(120, 120));
        notification.setPreferredSize(new java.awt.Dimension(80, 80));
        notification.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                notificationComponentResized(evt);
            }
        });
        top_panel.add(notification);
        notification.setBounds(1230, 30, 60, 60);

        rating_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rating_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/system/rating_icon.png"))); // NOI18N
        rating_icon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rating_icon.setMaximumSize(new java.awt.Dimension(120, 120));
        rating_icon.setMinimumSize(new java.awt.Dimension(120, 120));
        rating_icon.setPreferredSize(new java.awt.Dimension(80, 80));
        rating_icon.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                rating_iconComponentResized(evt);
            }
        });
        top_panel.add(rating_icon);
        rating_icon.setBounds(1150, 30, 60, 70);

        runner_background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        runner_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/system/darken_runner_background.png"))); // NOI18N
        runner_background.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        runner_background.setMaximumSize(new java.awt.Dimension(120, 120));
        runner_background.setMinimumSize(new java.awt.Dimension(120, 120));
        runner_background.setPreferredSize(new java.awt.Dimension(80, 80));
        runner_background.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                runner_backgroundComponentResized(evt);
            }
        });
        top_panel.add(runner_background);
        runner_background.setBounds(0, 0, 1400, 700);

        getContentPane().add(top_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        bottom_panel.setBackground(new java.awt.Color(255, 251, 233));
        bottom_panel.setPreferredSize(new java.awt.Dimension(1400, 640));
        bottom_panel.setLayout(null);

        revenue_text.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        revenue_text.setForeground(new java.awt.Color(0, 0, 0));
        revenue_text.setText("Revenue");
        bottom_panel.add(revenue_text);
        revenue_text.setBounds(60, 30, 650, 56);

        javax.swing.GroupLayout graph_panelLayout = new javax.swing.GroupLayout(graph_panel);
        graph_panel.setLayout(graph_panelLayout);
        graph_panelLayout.setHorizontalGroup(
            graph_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
        graph_panelLayout.setVerticalGroup(
            graph_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        bottom_panel.add(graph_panel);
        graph_panel.setBounds(60, 93, 650, 450);

        daily_button.setBackground(new java.awt.Color(255, 255, 255));
        daily_button.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        daily_button.setForeground(new java.awt.Color(0, 0, 0));
        daily_button.setText("Daily");
        daily_button.setAlignmentY(0.0F);
        daily_button.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        daily_button.setIconTextGap(0);
        daily_button.setMargin(new java.awt.Insets(0, 0, 0, 0));
        daily_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daily_buttonActionPerformed(evt);
            }
        });
        bottom_panel.add(daily_button);
        daily_button.setBounds(750, 30, 150, 45);

        monthly_button.setBackground(new java.awt.Color(255, 255, 255));
        monthly_button.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        monthly_button.setForeground(new java.awt.Color(0, 0, 0));
        monthly_button.setText("Monthly");
        monthly_button.setAlignmentY(0.0F);
        monthly_button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        monthly_button.setIconTextGap(0);
        monthly_button.setMargin(new java.awt.Insets(0, 0, 0, 0));
        monthly_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthly_buttonActionPerformed(evt);
            }
        });
        bottom_panel.add(monthly_button);
        monthly_button.setBounds(900, 30, 150, 45);

        quarterly_button.setBackground(new java.awt.Color(255, 255, 255));
        quarterly_button.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        quarterly_button.setForeground(new java.awt.Color(0, 0, 0));
        quarterly_button.setText("Quarterly");
        quarterly_button.setAlignmentY(0.0F);
        quarterly_button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        quarterly_button.setIconTextGap(0);
        quarterly_button.setMargin(new java.awt.Insets(0, 0, 0, 0));
        quarterly_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quarterly_buttonActionPerformed(evt);
            }
        });
        bottom_panel.add(quarterly_button);
        quarterly_button.setBounds(1050, 30, 150, 45);

        yearly_button.setBackground(new java.awt.Color(255, 255, 255));
        yearly_button.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        yearly_button.setForeground(new java.awt.Color(0, 0, 0));
        yearly_button.setText("Yearly");
        yearly_button.setAlignmentY(0.0F);
        yearly_button.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        yearly_button.setIconTextGap(0);
        yearly_button.setMargin(new java.awt.Insets(0, 0, 0, 0));
        yearly_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearly_buttonActionPerformed(evt);
            }
        });
        bottom_panel.add(yearly_button);
        yearly_button.setBounds(1200, 30, 150, 45);

        total_delivery_text.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        total_delivery_text.setForeground(new java.awt.Color(0, 0, 0));
        total_delivery_text.setText("Total Delivery");
        bottom_panel.add(total_delivery_text);
        total_delivery_text.setBounds(750, 120, 300, 42);

        total_earnings_text.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        total_earnings_text.setForeground(new java.awt.Color(0, 0, 0));
        total_earnings_text.setText("Total Earnings");
        bottom_panel.add(total_earnings_text);
        total_earnings_text.setBounds(1060, 120, 290, 42);

        total_delivery_value.setBackground(new java.awt.Color(255, 251, 233));
        total_delivery_value.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        total_delivery_value.setForeground(new java.awt.Color(0, 0, 0));
        total_delivery_value.setText("123,123");
        total_delivery_value.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        total_delivery_value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total_delivery_valueActionPerformed(evt);
            }
        });
        bottom_panel.add(total_delivery_value);
        total_delivery_value.setBounds(750, 160, 290, 75);

        total_earnings_value.setBackground(new java.awt.Color(255, 251, 233));
        total_earnings_value.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        total_earnings_value.setForeground(new java.awt.Color(0, 0, 0));
        total_earnings_value.setText("RM 123,123");
        total_earnings_value.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        total_earnings_value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total_earnings_valueActionPerformed(evt);
            }
        });
        bottom_panel.add(total_earnings_value);
        total_earnings_value.setBounds(1060, 160, 290, 75);

        recent_delivery_text.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        recent_delivery_text.setForeground(new java.awt.Color(0, 0, 0));
        recent_delivery_text.setText("Recent Delivery");
        bottom_panel.add(recent_delivery_text);
        recent_delivery_text.setBounds(750, 240, 590, 42);

        jScrollPane1.setBackground(new java.awt.Color(255, 251, 233));
        jScrollPane1.setForeground(new java.awt.Color(255, 251, 233));
        bottom_panel.add(jScrollPane1);
        jScrollPane1.setBounds(750, 290, 590, 330);

        getContentPane().add(bottom_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, -1, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logo_lightComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_logo_lightComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_logo_lightComponentResized

    private void daily_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daily_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_daily_buttonActionPerformed

    private void monthly_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthly_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monthly_buttonActionPerformed

    private void quarterly_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quarterly_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quarterly_buttonActionPerformed

    private void yearly_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearly_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearly_buttonActionPerformed

    private void total_delivery_valueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total_delivery_valueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_total_delivery_valueActionPerformed

    private void total_earnings_valueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total_earnings_valueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_total_earnings_valueActionPerformed

    private void runner_backgroundComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_runner_backgroundComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_runner_backgroundComponentResized

    private void backComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_backComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_backComponentResized

    private void notificationComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_notificationComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_notificationComponentResized

    private void rating_iconComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_rating_iconComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_rating_iconComponentResized

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RunnerDeliverHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RunnerDeliverHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RunnerDeliverHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RunnerDeliverHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RunnerDeliverHistory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JPanel bottom_panel;
    private javax.swing.JButton daily_button;
    private javax.swing.JLabel delivery_history;
    private javax.swing.JPanel graph_panel;
    private javax.swing.JLabel home_page;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logo_light;
    private javax.swing.JButton monthly_button;
    private javax.swing.JLabel notification;
    private javax.swing.JButton quarterly_button;
    private javax.swing.JLabel rating_icon;
    private javax.swing.JLabel recent_delivery_text;
    private javax.swing.JLabel revenue_text;
    private javax.swing.JLabel runner_background;
    private javax.swing.JPanel top_panel;
    private javax.swing.JLabel total_delivery_text;
    private javax.swing.JTextField total_delivery_value;
    private javax.swing.JLabel total_earnings_text;
    private javax.swing.JTextField total_earnings_value;
    private javax.swing.JButton yearly_button;
    // End of variables declaration//GEN-END:variables
}
