/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frontend.utility;

import backend.file_io.PictureIO;
import backend.utility.Utility;
import java.awt.Color;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author limbengrhui
 */
public class RatingStarPanel extends javax.swing.JPanel {

    private static double ratings;
    /**
     * Creates new form RatingStarPanel
     * 
     * @param inputRatings The ratings of the vendor
     */
    public RatingStarPanel(double inputRatings) {
        
        // Save ratings
        ratings = inputRatings;
        
        // Render GUI components
        initComponents();
        
        // Set the stars
        setStar(star1, 0.0, 1.0);
        setStar(star2, 1.0, 2.0);
        setStar(star3, 2.0, 3.0);
        setStar(star4, 3.0, 4.0);
        setStar(star5, 4.0, 5.0);
    }
    
    /**
     * The method to set the star label with icon.
     * 
     * @param star The JLabel to be inserted with icon
     * @param lowerRange The minimum value represented by the star
     * @param upperRange The maximum value represented by the star
     */
    private static void setStar(JLabel star, double lowerRange, double upperRange) {
        
        // Get directory to /asset/system file
        File[] directory = new File(PictureIO.PARENT_PATH_TO_SYSTEM_DIRECTORY).listFiles();
        
        // First prepare the different types of star
        File emptyStarFile = Utility.retrieveFileWithoutExtension(directory, "empty_star_icon");
        ImageIcon emptyStar = new ImageIcon(emptyStarFile.getAbsolutePath());
        
        File halfStarFile = Utility.retrieveFileWithoutExtension(directory, "half_star_icon");
        ImageIcon halfStar = new ImageIcon(halfStarFile.getAbsolutePath());
        
        File fullStarFile = Utility.retrieveFileWithoutExtension(directory, "full_star_icon");
        ImageIcon fullStar = new ImageIcon(fullStarFile.getAbsolutePath());
        
        // Taking a lower range of 4.0 and upper range of 5.0 as example
        
        // When the ratings is lower than 4.25
        if (ratings < lowerRange + 0.25) {
        
            // We put enpty star
            star.setIcon(emptyStar);
            
        // When the ratings is higher than 4.75
        } else if (ratings > upperRange - 0.25) {
        
            // We put full star
            star.setIcon(fullStar);
            
        // When the ratings falls between 4.25 to 4.75
        } else {
            
            // We put half star
            star.setIcon(halfStar);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        star1 = new javax.swing.JLabel();
        star2 = new javax.swing.JLabel();
        star3 = new javax.swing.JLabel();
        star4 = new javax.swing.JLabel();
        star5 = new javax.swing.JLabel();

        setBackground(new Color(0, 0, 0, 0));
        setName("backgroundPanel"); // NOI18N
        setPreferredSize(new java.awt.Dimension(190, 30));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        star1.setBackground(new java.awt.Color(204, 255, 204));
        star1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(star1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        star2.setBackground(new java.awt.Color(204, 255, 204));
        star2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(star2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 30, 30));

        star3.setBackground(new java.awt.Color(204, 255, 204));
        star3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(star3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 30, 30));

        star4.setBackground(new java.awt.Color(204, 255, 204));
        star4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(star4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 30, 30));

        star5.setBackground(new java.awt.Color(204, 255, 204));
        star5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(star5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 30, 30));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel star1;
    private javax.swing.JLabel star2;
    private javax.swing.JLabel star3;
    private javax.swing.JLabel star4;
    private javax.swing.JLabel star5;
    // End of variables declaration//GEN-END:variables
}
