/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frontend.admin;

import backend.entity.Customer;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import java.util.stream.Collectors;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Chun Ming (TP068983), Beng Rhui (TP068495)
 */
public class CustomerCreditPanel extends javax.swing.JPanel {

    private static ArrayList<Customer> customerList;
    
    /**
     * Creates new form CustomerCreditPanel
     */
    public CustomerCreditPanel() {

        // Initialize customer list
        customerList = Customer.getCustomerList();

        // Render GUI components
        initComponents();
        
        // Update panels
        updatePanel();
    }

    public static void updatePanel() {
        
        // Clear the current panel
        customerCreditPanel.removeAll();
        
        // Loop through each stall
        for (Customer customer : customerList) {
            
            // Create the corresponding stall details panel
            JPanel individualCreditPanel = new CustomerCreditDetails(customer);
            
            // Add the individual panel to the container
            customerCreditPanel.add(individualCreditPanel);
        }
        
        // If there is no user, 
        if (customerList.isEmpty()) {
            
            // Generate a empty panel and label to indicate that no user exists
            JPanel emptyPanel = new JPanel();
            JLabel emptyLabel = new JLabel("No customer record exists in the system.");
            emptyLabel.setFont(new Font("Arial", Font.PLAIN, 24));
            emptyPanel.setBackground(new Color(255, 251, 233));
            
            // Add the label to the panel
            emptyPanel.add(emptyLabel);
            
            // Add the panel to the container
            customerCreditPanel.add(emptyPanel);
            
        } else if (customerList.size() < 4) {
        
            // Start a loop to create empty panels to be placed inside the grid layout
            for (int i = customerList.size() + 1; i < 7; i ++) {
                
                // Create the empty panel
                JPanel emptyPanel = new JPanel();
                emptyPanel.setBackground(new Color(255, 251, 233));
                
                // Add the empty panel to the container
                customerCreditPanel.add(emptyPanel);
            }
        }
        
        // Refresh the pane after all actions
        customerCreditPanel.revalidate();
        customerCreditPanel.repaint();
    }
    
    private void filterByName(String name) {

        // Filter customer based on name
        customerList = Customer.getCustomerList().stream()
                .filter(customer -> customer.getName().toLowerCase().contains(name.toLowerCase()))
                .collect(Collectors.toCollection(ArrayList::new));

        // Update panel after filter
        updatePanel();
    }

    private void filterByContactNumber(String contactNumber) {

        // Filter customer based on contact number (ignore '-' during search)
        customerList = Customer.getCustomerList().stream()
                .filter(
                        customer -> customer.getContactNumber().replace("-", "").
                                contains(contactNumber.replace("-", "")))
                .collect(Collectors.toCollection(ArrayList::new));

        // Update panel after filter
        updatePanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTitle = new javax.swing.JLabel();
        searchNameLabel = new javax.swing.JLabel();
        searchNameField = new javax.swing.JTextField();
        searchContactNumberLabel = new javax.swing.JLabel();
        searchContactNumberField = new javax.swing.JTextField();
        customerCreditScrollPane = new javax.swing.JScrollPane();
        customerCreditPanel = new javax.swing.JPanel();
        backButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 251, 233));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelTitle.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        panelTitle.setText("Customer Credit");
        add(panelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        searchNameLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        searchNameLabel.setText("<html>Search by name:</html>");
        add(searchNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 80, 70));

        searchNameField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        searchNameField.setForeground(new java.awt.Color(204, 204, 204));
        searchNameField.setText("Enter Name Here");
        searchNameField.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), javax.swing.BorderFactory.createEmptyBorder(2, 15, 2, 15)));
        searchNameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchNameFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchNameFieldFocusLost(evt);
            }
        });
        searchNameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchNameFieldKeyReleased(evt);
            }
        });
        add(searchNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 660, 50));

        searchContactNumberLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        searchContactNumberLabel.setText("<html>Search by contact no:</html>");
        add(searchContactNumberLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 110, 120, 70));

        searchContactNumberField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        searchContactNumberField.setForeground(new java.awt.Color(204, 204, 204));
        searchContactNumberField.setText("Enter Contact No (e.g. 012-3456789)");
        searchContactNumberField.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), javax.swing.BorderFactory.createEmptyBorder(2, 15, 2, 15)));
        searchContactNumberField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchContactNumberFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchContactNumberFieldFocusLost(evt);
            }
        });
        searchContactNumberField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchContactNumberFieldKeyReleased(evt);
            }
        });
        add(searchContactNumberField, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 120, 340, 50));

        customerCreditScrollPane.setBackground(new java.awt.Color(255, 251, 233));
        customerCreditScrollPane.setBorder(null);
        customerCreditScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        customerCreditScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        customerCreditPanel.setBackground(new java.awt.Color(255, 251, 233));
        customerCreditPanel.setLayout(new java.awt.GridLayout(0, 3, 10, 10));
        customerCreditScrollPane.setViewportView(customerCreditPanel);

        add(customerCreditScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 1220, 450));

        backButton.setBackground(Color.WHITE);
        backButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        backButton.setText("Back");
        backButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        backButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backButton.setFocusPainted(false);
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backButtonMouseExited(evt);
            }
        });
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 680, 210, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed

        // Return to main page
        MainPage.setCard("actionPanel");
    }//GEN-LAST:event_backButtonActionPerformed

    private void backButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseEntered

        // Change the colour of the button
        backButton.setBackground(new Color(206, 171, 147));
    }//GEN-LAST:event_backButtonMouseEntered

    private void backButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseExited

        // Change the colour of the button
        backButton.setBackground(Color.WHITE);
    }//GEN-LAST:event_backButtonMouseExited

    private void searchNameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchNameFieldFocusGained

        // If prompt is still there
        if (searchNameField.getText().equals("Enter Name Here")) {
            
            // Remove the prompt
            searchNameField.setText("");
            
            // Change text to black
            searchNameField.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_searchNameFieldFocusGained

    private void searchNameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchNameFieldFocusLost

        // If input is empty
        if (searchNameField.getText().isBlank()) {
            
            // Set prompt
            searchNameField.setText("Enter Name Here");
            
            // Change text to grey
            searchNameField.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_searchNameFieldFocusLost

    private void searchContactNumberFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchContactNumberFieldFocusGained

        // If prompt is still there
        if (searchContactNumberField.getText().equals("Enter Contact No (e.g. 012-3456789)")) {
            
            // Remove the prompt
            searchContactNumberField.setText("");
            
            // Change text to black
            searchContactNumberField.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_searchContactNumberFieldFocusGained

    private void searchContactNumberFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchContactNumberFieldFocusLost

        // If input is empty
        if (searchContactNumberField.getText().isBlank()) {
            
            // Set prompt
            searchContactNumberField.setText("Enter Contact No (e.g. 012-3456789)");
            
            // Change text to grey
            searchContactNumberField.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_searchContactNumberFieldFocusLost

    private void searchNameFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchNameFieldKeyReleased
        
        // Clear the contact number field
        searchContactNumberField.setText("Enter Contact No (e.g. 012-3456789)");
        searchContactNumberField.setForeground(new Color(204, 204, 204));
        
        // Filter panel based on input
        String input = searchNameField.getText();
        filterByName(input);
    }//GEN-LAST:event_searchNameFieldKeyReleased

    private void searchContactNumberFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchContactNumberFieldKeyReleased

        // Clear the name field
        searchNameField.setText("Enter Name Here");
        searchNameField.setForeground(new Color(204, 204, 204));
        
        // Filter panel based on input
        String input = searchContactNumberField.getText();
        filterByContactNumber(input);
    }//GEN-LAST:event_searchContactNumberFieldKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private static javax.swing.JPanel customerCreditPanel;
    private javax.swing.JScrollPane customerCreditScrollPane;
    private javax.swing.JLabel panelTitle;
    private javax.swing.JTextField searchContactNumberField;
    private javax.swing.JLabel searchContactNumberLabel;
    private javax.swing.JTextField searchNameField;
    private javax.swing.JLabel searchNameLabel;
    // End of variables declaration//GEN-END:variables
}
