/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend.admin;

import backend.entity.Admin;
import frontend.home_page.HomePage;
import frontend.pop_up.SystemPopUp;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Graphics;
import javax.swing.JFrame;

/**
 *
 * @author Chun Ming (TP068983), Beng Rhui (TP068495)
 */
public class MainPage extends javax.swing.JFrame {

    public static JFrame currentFrame;
    private static Admin currentAdmin;
    private static CardLayout cardLayout;
    
    /**
     * Creates new form MainPage
     */
    public MainPage() {
        
        // Render GUI components
        initComponents();
        
        // Initialize variables
        currentFrame = this;

        // Prepare the additional card panels
        ActionPanel actionPanel = new ActionPanel();
        UserListPanel userlistPanel = new UserListPanel();
        CustomerCreditPanel customerCreditPanel = new CustomerCreditPanel();
        StallListPanel storePanel = new StallListPanel();
       
        // Add the card panels to the card container panel
        cardLayoutContainer.add(actionPanel, "actionPanel");
        cardLayoutContainer.add(userlistPanel, "userlistPanel");
        cardLayoutContainer.add(customerCreditPanel, "customerCreditPanel");
        cardLayoutContainer.add(storePanel, "storePanel");
        
        // Display action page (main page) as default
        cardLayout = (CardLayout) cardLayoutContainer.getLayout();
        cardLayout.show(cardLayoutContainer, "actionPanel");
    }
    
    /**
     * This method helps to retrieve the admin associated with the current frame.
     * @return THe Admin associated with the current frame
     */
    public static Admin getAdmin() {
        return currentAdmin;
    }
    
    /**
     * This method helps to initialize the admin.
     * @param admin 
     */
    public static void setAdmin(Admin admin) {
        currentAdmin = admin;
    }
    
    /**
     * This method helps to set the card being displayed.
     * @param cardName The name of the card that will be displayed
     */
    public static void setCard(String cardName) {
        cardLayout.show(cardLayoutContainer, cardName);
        currentFrame.revalidate();
        currentFrame.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardLayoutContainer = new javax.swing.JPanel() {
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
            }
        };
        backgroundPicture = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Food Court System");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cardLayoutContainer.setBackground(new Color(0, 0, 0, 0));
        cardLayoutContainer.setLayout(new java.awt.CardLayout());
        getContentPane().add(cardLayoutContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 800));

        backgroundPicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/system/admin_background.png"))); // NOI18N
        getContentPane().add(backgroundPicture, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

        // Show message to confirm logout
        SystemPopUp logoutConfirmation = new SystemPopUp(
                currentFrame,
                "Logout from System",
                "Are you sure you wish to logout from the system?",
                new String[]{"No", "Yes"}
        );
        logoutConfirmation.setVisible(true);
        
        // Get the status of the notification
        int status = logoutConfirmation.getStatus();
        
        // If "Yes" is chosen
        if (status == 1) {
            
            // Display a message to indicate that logout is successful
            SystemPopUp successLogout = new SystemPopUp(
                currentFrame,
                "Logout Success",
                "Thank you for using the system!",
                new String[]{"OK"}
            );
            successLogout.setVisible(true);
            
            // Redirect users to home page
            HomePage homePage = new HomePage();
            homePage.setVisible(true);
            homePage.setLocationRelativeTo(this);
            
            // Dispose the parent frame
            currentFrame.dispose();

            // Set the runner instance to null (to avoid any errors when login again)
            setAdmin(null);
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundPicture;
    private static javax.swing.JPanel cardLayoutContainer;
    // End of variables declaration//GEN-END:variables
}
